# Generated by Trae Work
"""
MMEDIT ALM (Audio Language Model) + Content Encoder

核心思想: 使用 Qwen2-Audio 7B 作为多模态编码器，
联合处理源音频 x_in 和文本指令 y，产生跨模态对齐表示 H。

从 H 中导出两种条件信号:
1. 全局上下文 c_global = AvgPool(H) → 通过 AdaLN 调制整个网络
2. 细粒度序列特征 H_seq = H → 通过联合注意力与音频潜在交互

另外，源音频 VAE 潜在 (time_aligned_context) 直接与噪声潜在拼接，
为扩散模型提供未编辑的参考音频。

参考文件:
- models/content_encoder/llm_encoder.py
- models/content_encoder/content_encoder.py
- models/content_adapter.py
"""

from typing import Any
import torch
import torch.nn as nn
import librosa
import numpy as np
from transformers import AutoProcessor, Qwen2AudioForConditionalGeneration
import os


# ============================================================
# Qwen2-Audio 嵌入器 (ALM 核心)
# ============================================================

class Qwen2AudioEmbedder(nn.Module):
    """
    基于 Qwen2-Audio 的多模态编码器。

    输入: 文本指令 + 源音频
    输出: 跨模态对齐的序列嵌入 H ∈ R^{L_q × D_q}

    流程:
        1. 构建对话格式 (system prompt + audio + text)
        2. processor 批量处理 (tokenize + audio feature extraction)
        3. Qwen2-Audio 模型前向传播
        4. 取最后一层隐藏状态
        5. 线性投影到目标维度 embed_dim

    注意:
        - Qwen2-Audio 本身是冻结的 (requires_grad=False)
        - 只有投影层 proj 参与训练
        - 输出序列被截断/填充到固定长度 max_length
    """
    def __init__(
        self,
        model_path: str,
        embed_dim: int = 256,
        max_length: int = 320,
        dtype: torch.dtype = torch.float,
        device: str = "cuda"
    ):
        super().__init__()
        self.max_length = max_length
        self.device = device
        self.embed_dim = embed_dim

        # 加载 Qwen2-Audio 模型 (冻结)
        self.model = Qwen2AudioForConditionalGeneration.from_pretrained(
            model_path,
            torch_dtype=dtype,
            device_map={"": int(os.environ.get("LOCAL_RANK", 0))}
        )
        self.model.requires_grad_(False)
        self.model.eval()
        self.processor = AutoProcessor.from_pretrained(model_path)

        # 投影层: 4096 (Qwen2-Audio hidden dim) → embed_dim
        # 这一层是可训练的
        self.proj = nn.Linear(4096, embed_dim, device=device, dtype=dtype)

    def forward(self, text: list[str], audio_data: list) -> dict[str, torch.Tensor]:
        """
        Args:
            text: 文本描述列表 (batch)
            audio_data: 音频数据列表，每个元素是 numpy 数组或 Tensor
        Returns:
            {"output": [B, max_length, embed_dim], "mask": [B, max_length]}
        """
        output, mask = self.encode(text, audio_data)
        output = self.projection(output)
        return {"output": output, "mask": mask}

    def encode(self, text: list[str], audio_data: list) -> tuple[torch.Tensor, torch.Tensor]:
        """
        编码文本和音频到嵌入空间 (未投影)。

        完整处理流程:
        1. 重采样音频到 16kHz (Qwen2-Audio 要求)
        2. 构建对话模板: [audio + text instruction]
        3. processor 批量 tokenize + 音频处理
        4. 模型前向，提取最后一层隐藏状态
        5. 截断/填充到固定 max_length
        """
        batch_size = len(text)

        # 1. 音频预处理: 重采样到 16kHz
        processed_audios = []
        for audio in audio_data:
            if isinstance(audio, torch.Tensor):
                audio = audio.cpu().numpy()
            audio = librosa.resample(audio, orig_sr=24000, target_sr=16000)
            processed_audios.append(audio)

        # 2. 构建对话文本 (chat template)
        conversations = []
        for txt in text:
            conversation = [
                {"role": "user", "content": [
                    {"type": "audio", "audio": None},
                    {"type": "text", "text": txt}
                ]}
            ]
            formatted_text = self.processor.apply_chat_template(
                conversation, add_generation_prompt=True, tokenize=False
            )
            conversations.append(formatted_text)

        with torch.no_grad():
            # 3. processor 批量处理
            inputs = self.processor(
                text=conversations,
                audio=processed_audios,
                return_tensors="pt",
                sampling_rate=16000,
                padding=True,
                truncation=True
            )
            inputs = {k: v.to(self.device) for k, v in inputs.items()}

            # 4. 模型前向，获取隐藏状态
            outputs = self.model(
                input_ids=inputs["input_ids"],
                attention_mask=inputs["attention_mask"],
                input_features=inputs["input_features"],
                feature_attention_mask=inputs["feature_attention_mask"],
                output_hidden_states=True,
            )

            # 提取最后一层隐藏状态
            hidden_states_full = outputs.hidden_states[-1]

            # 5. 截断或填充到固定长度 max_length
            current_len = hidden_states_full.shape[1]
            if current_len > self.max_length:
                embs = hidden_states_full[:, :self.max_length, :]
            else:
                pad_width = self.max_length - current_len
                padding = torch.zeros(
                    hidden_states_full.shape[0],
                    pad_width,
                    hidden_states_full.shape[2],
                    device=self.device,
                    dtype=hidden_states_full.dtype
                )
                embs = torch.cat([hidden_states_full, padding], dim=1)

            # 处理 attention mask
            attention_mask = inputs["attention_mask"]
            if current_len > self.max_length:
                masks = attention_mask[:, :self.max_length].bool()
            else:
                pad_width = self.max_length - current_len
                mask_padding = torch.zeros(
                    attention_mask.shape[0],
                    pad_width,
                    device=self.device,
                    dtype=torch.bool
                )
                masks = torch.cat([attention_mask.bool(), mask_padding], dim=1)

        return embs, masks

    def projection(self, x: torch.Tensor) -> torch.Tensor:
        """将 4096 维嵌入映射到指定 embed_dim"""
        return self.proj(x)


# ============================================================
# Content Encoder (统一内容编码)
# ============================================================

class ContentEncoder(nn.Module):
    """
    内容编码器，管理多种模态的编码器。

    在 audio_editing 任务中:
    - text_encoder = Qwen2AudioEmbedder (处理 caption + audio → 全局语义)
    - audio_encoder = StableVAEProjectorWrapper (处理 audio → 时间对齐的潜在)

    输出四种信号:
    1. content: ALM 输出的序列嵌入 (全局语义条件)  [B, L_text, D]
    2. content_mask: 对应掩码                      [B, L_text]
    3. length_aligned_content: 源音频 VAE 潜在 (时间对齐条件) [B, L_lat, D]
    4. time_aligned_content_mask: 对应掩码              [B, L_lat]
    """
    def __init__(
        self,
        embed_dim: int,
        text_encoder: nn.Module = None,
        llm_encoder: nn.Module = None,
        video_encoder: nn.Module = None,
        midi_encoder: nn.Module = None,
        phoneme_encoder: nn.Module = None,
        pitch_encoder: nn.Module = None,
        audio_encoder: nn.Module = None
    ):
        super().__init__()
        self.embed_dim = embed_dim
        self.text_encoder = text_encoder    # ALM (Qwen2-Audio)
        self.midi_encoder = midi_encoder
        self.phoneme_encoder = phoneme_encoder
        self.pitch_encoder = pitch_encoder
        self.audio_encoder = audio_encoder  # VAE Projector
        self.video_encoder = video_encoder

    def encode_content(
        self,
        batch_content: list[Any],
        batch_task: list[str],
        device: str | torch.device
    ) -> dict[str, torch.Tensor]:
        """
        编码批量内容。

        对于 audio_editing 任务:
        batch_content[i] = {"audio": waveform_tensor, "caption": "add a dog bark"}
        batch_task[i] = "audio_editing"

        两个编码路径并行:
        path A: caption + audio → text_encoder (Qwen2Audio) → 全局语义嵌入
        path B: audio → audio_encoder (VAE + proj) → 时间对齐的潜在特征
        """
        batch_content_output = []
        batch_content_mask = []
        batch_la_content_output = []
        batch_la_content_output_mask = []
        zero_la_content = torch.zeros(1, 1, self.embed_dim, device=device)

        for i, (content, task) in enumerate(zip(batch_content, batch_task)):
            if task == "audio_editing":
                raw_waveform = torch.as_tensor(content["audio"]).float()
                waveform_with_batch_dim = raw_waveform.unsqueeze(0).to(device)
                waveform_lengths = torch.as_tensor([raw_waveform.shape[0]])

                # Path A: ALM 编码 (caption + audio → 全局语义)
                # Note: text encoder 实际上是 audiollm encoder
                content_output_dict = self.text_encoder(
                    [content["caption"]], waveform_with_batch_dim
                )

                # Path B: VAE 编码 (audio → 时间对齐的潜在)
                audio_dict = {
                    "waveform": waveform_with_batch_dim,
                    "waveform_lengths": waveform_lengths
                }
                audio_output_dict = self.audio_encoder(**audio_dict)
                la_content_output_dict = {
                    "output": audio_output_dict["output"],
                    "mask": audio_output_dict["mask"]
                }

            batch_content_output.append(content_output_dict["output"][0])
            batch_content_mask.append(content_output_dict["mask"][0])
            batch_la_content_output.append(la_content_output_dict["output"][0])
            batch_la_content_output_mask.append(
                la_content_output_dict.get("mask", zero_la_content)[0]
            )

        # Pad 到统一长度
        batch_content_output = nn.utils.rnn.pad_sequence(
            batch_content_output, batch_first=True, padding_value=0
        )
        batch_content_mask = nn.utils.rnn.pad_sequence(
            batch_content_mask, batch_first=True, padding_value=False
        )
        batch_la_content_output = nn.utils.rnn.pad_sequence(
            batch_la_content_output, batch_first=True, padding_value=0
        )
        batch_la_content_output_mask = nn.utils.rnn.pad_sequence(
            batch_la_content_output_mask, batch_first=True, padding_value=False
        )

        return {
            "content": batch_content_output,               # [B, L_text, D]  ALM全局语义
            "content_mask": batch_content_mask,            # [B, L_text]
            "length_aligned_content": batch_la_content_output,  # [B, L_lat, D]  VAE时间对齐
            "time_aligned_content_mask": batch_la_content_output_mask  # [B, L_lat]
        }


# ============================================================
# Batched Content Encoder (批量优化版)
# ============================================================

class BatchedContentEncoder(ContentEncoder):
    """
    批量优化版本的 ContentEncoder。
    将整个 batch 的文本和音频一次性送入 ALM，提高效率。
    """
    def encode_content(
        self,
        batch_content: list[dict],
        batch_task: list[str],
        device: str | torch.device
    ):
        assert all(task == "audio_editing" for task in batch_task), \
            "BatchedContentEncoder now are only support audio_editing"

        zero_la_content = torch.zeros(1, 1, self.embed_dim, device=device)

        # 收集所有 caption 和 waveform
        captions = []
        waveforms = []
        waveform_lengths = []
        for content in batch_content:
            raw_waveform = torch.as_tensor(content["audio"]).float().to(device)
            captions.append(content["caption"])
            waveforms.append(raw_waveform)
            waveform_lengths.append(raw_waveform.shape[0])

        # Path A: 批量 ALM 编码
        content_output_dict = self.text_encoder(captions, waveforms)

        # Path B: 逐个 VAE 编码 (VAE 内部处理 padding)
        batch_la_content_output = []
        batch_la_content_output_mask = []
        for i in range(len(batch_content)):
            audio_dict = {
                "waveform": waveforms[i].unsqueeze(0),
                "waveform_lengths": torch.as_tensor([waveform_lengths[i]], device=device)
            }
            audio_output_dict = self.audio_encoder(**audio_dict)
            batch_la_content_output.append(audio_output_dict["output"][0])
            batch_la_content_output_mask.append(audio_output_dict["mask"][0])

        # Pad VAE 输出
        batch_la_content_output = nn.utils.rnn.pad_sequence(
            batch_la_content_output, batch_first=True, padding_value=0
        )
        batch_la_content_output_mask = nn.utils.rnn.pad_sequence(
            batch_la_content_output_mask, batch_first=True, padding_value=False
        )

        return {
            "content": content_output_dict["output"],          # [B, L_text, D]
            "content_mask": content_output_dict["mask"],       # [B, L_text]
            "length_aligned_content": batch_la_content_output,  # [B, L_lat, D]
            "time_aligned_content_mask": batch_la_content_output_mask
        }


# ============================================================
# ALM 输出注入 DiT 的流程说明
# ============================================================
"""
ALM 输出通过以下方式注入 MMDiT:

1. **全局条件 (AdaLN 调制)**
   c_global = AvgPool(H)  → text_cond_proj → global_cond_mlp
   与时间步嵌入相加: global_c = t_embed(t) + c_global
   通过每个 Transformer 块的 AdaLN 调制 (shift + scale)

2. **细粒度序列条件 (联合自注意力)**
   H_seq = H  → text_input_proj → text_f
   在 JointBlock 中，与音频潜在 latent 沿序列维拼接，
   通过共享的自注意力层交互，实现事件级定位

3. **时间对齐条件 (通道拼接)**
   源音频 VAE 潜在 z_in → audio_encoder (proj) → time_aligned_context
   与噪声潜在 z_t 沿最后一维拼接后，通过 audio_input_proj 输入网络
   这提供了未编辑区域的参考，保证编辑前后一致性

关键代码位置 (在 mmdit_back.py 的 predict_flow 中):
    # 时间对齐条件拼接
    x = torch.cat([x.transpose(1, 2), time_aligned_context], dim=-1)
    latent = self.audio_input_proj(x)

    # 全局条件
    global_c = self.global_cond_mlp(text_f_c)
    global_c = self.t_embed(timesteps).unsqueeze(1) + global_c.unsqueeze(1)

    # 联合注意力块
    for block in self.joint_blocks:
        latent, text_f = block(latent, text_f, global_c, extended_c, self.latent_rot)
"""
