# Generated by Trae Work
"""
MMEDIT MMDiT + DDPM 扩散模型

核心架构:
- 扩散公式: DDPM (速度预测 v_prediction)
- 主干: MMDiT (Multi-Modal Diffusion Transformer)
  - Joint Blocks: 音频潜在 + 文本嵌入 联合自注意力
  - Single Blocks: 仅音频自注意力 (细化时间/频谱连贯性)
  - AdaLN 调制: 全局条件 (时间步 + ALM 全局语义)

DDPM 数学底层:
    z_t = sqrt(ᾱ_t) * z_0 + sqrt(1 - ᾱ_t) * ε,   ε ~ N(0, I)
    v = sqrt(ᾱ_t) * ε - sqrt(1 - ᾱ_t) * z_0    (速度预测目标)

ALM 输出注入方式 (三种):
1. 全局条件: c_global = AvgPool(H) → AdaLN 调制整个网络
2. 序列条件: H_seq = H → 联合自注意力
3. 时间对齐条件: z_in (源音频VAE潜在) → 与噪声潜在通道拼接

参考文件:
- models/diffusion.py
- models/dit/mmdit_back.py
- models/dit/mmdit_layers.py
"""

import logging
from dataclasses import dataclass
from typing import Optional, Sequence, Any, Union
import random

from tqdm import tqdm
import torch
import torch.nn as nn
import torch.nn.functional as F
from einops import rearrange
from einops.layers.torch import Rearrange
import diffusers.schedulers as noise_schedulers
from diffusers.schedulers.scheduling_utils import SchedulerMixin
from diffusers.utils.torch_utils import randn_tensor


# ============================================================
# 工具函数
# ============================================================

def create_mask_from_length(lengths: torch.Tensor, max_length: int = None) -> torch.Tensor:
    if max_length is None:
        max_length = lengths.max().item()
    batch_size = lengths.shape[0]
    mask = torch.arange(max_length, device=lengths.device).unsqueeze(0).expand(batch_size, -1)
    mask = mask < lengths.unsqueeze(1)
    return mask.float()


def loss_with_mask(loss: torch.Tensor, mask: torch.Tensor, reduce: bool = True) -> torch.Tensor:
    """带掩码的 loss 计算"""
    if mask is None:
        if reduce:
            return loss.mean()
        return loss
    # loss: [B, C, T], mask: [B, T]
    mask = mask.unsqueeze(1)  # [B, 1, T]
    loss = loss * mask
    if reduce:
        return loss.sum() / (mask.sum() * loss.shape[1] + 1e-8)
    return loss


# ============================================================
# RMSNorm
# ============================================================

class RMSNorm(nn.Module):
    def __init__(self, dim: int, eps: float = 1e-6):
        super().__init__()
        self.eps = eps
        self.weight = nn.Parameter(torch.ones(dim))

    def forward(self, x):
        rms = torch.sqrt(torch.mean(x ** 2, dim=-1, keepdim=True) + self.eps)
        x = x / rms * self.weight
        return x


# ============================================================
# RoPE (Rotary Position Embedding)
# ============================================================

def compute_rope_rotations(
    length: int,
    dim: int,
    theta: int,
    *,
    freq_scaling: float = 1.0,
    device: Union[torch.device, str] = 'cpu'
) -> torch.Tensor:
    """计算 RoPE 旋转矩阵"""
    assert dim % 2 == 0
    with torch.amp.autocast(device_type='cuda', enabled=False):
        pos = torch.arange(length, dtype=torch.float32, device=device)
        freqs = 1.0 / (theta ** (torch.arange(0, dim, 2, dtype=torch.float32, device=device) / dim))
        freqs *= freq_scaling
        rot = torch.einsum('..., f -> ... f', pos, freqs)
        rot = torch.stack([torch.cos(rot), -torch.sin(rot), torch.sin(rot), torch.cos(rot)], dim=-1)
        rot = rearrange(rot, 'n d (i j) -> 1 n d i j', i=2, j=2)
        return rot


def apply_rope(x: torch.Tensor, rot: torch.Tensor) -> torch.Tensor:
    """应用 RoPE 到 Q/K"""
    with torch.amp.autocast(device_type='cuda', enabled=False):
        _x = x.float()
        _x = _x.view(*_x.shape[:-1], -1, 1, 2)
        x_out = rot[..., 0] * _x[..., 0] + rot[..., 1] * _x[..., 1]
        return x_out.reshape(*x.shape).to(dtype=x.dtype)


# ============================================================
# 时间步嵌入
# ============================================================

class TimestepEmbedder(nn.Module):
    """
    将标量时间步嵌入为向量表示。
    正弦位置编码 + 2层 MLP
    """
    def __init__(self, dim: int, frequency_embedding_size: int = 256, max_period: int = 10000):
        super().__init__()
        self.mlp = nn.Sequential(
            nn.Linear(frequency_embedding_size, dim),
            nn.SiLU(),
            nn.Linear(dim, dim),
        )
        self.dim = dim
        self.max_period = max_period
        assert dim % 2 == 0, 'dim must be even.'

        with torch.autocast('cuda', enabled=False):
            initial_freqs = 1.0 / (10000 ** (torch.arange(0, frequency_embedding_size, 2, dtype=torch.float32) /
                                           frequency_embedding_size))
            freq_scale = 10000 / max_period
            freqs_tensor = freq_scale * initial_freqs
            self.register_buffer('freqs', freqs_tensor, persistent=False)

    def timestep_embedding(self, t: torch.Tensor) -> torch.Tensor:
        args = t[:, None].float() * self.freqs[None]
        embedding = torch.cat([torch.cos(args), torch.sin(args)], dim=-1)
        return embedding

    def forward(self, t: torch.Tensor) -> torch.Tensor:
        t_freq = self.timestep_embedding(t).to(t.dtype)
        t_emb = self.mlp(t_freq)
        return t_emb


# ============================================================
# 1D 卷积 (channel-last 格式)
# ============================================================

class ChannelLastConv1d(nn.Conv1d):
    """输入输出为 [B, T, C] 格式的 1D 卷积"""
    def forward(self, x: torch.Tensor) -> torch.Tensor:
        x = x.permute(0, 2, 1)   # [B, T, C] → [B, C, T]
        x = super().forward(x)
        x = x.permute(0, 2, 1)   # [B, C, T] → [B, T, C]
        return x


# ============================================================
# MLP & ConvMLP (SwiGLU 风格)
# ============================================================

class MLP(nn.Module):
    """SwiGLU MLP (文本/全局条件用)"""
    def __init__(self, dim: int, hidden_dim: int, multiple_of: int = 256):
        super().__init__()
        hidden_dim = int(2 * hidden_dim / 3)
        hidden_dim = multiple_of * ((hidden_dim + multiple_of - 1) // multiple_of)
        self.w1 = nn.Linear(dim, hidden_dim, bias=False)
        self.w2 = nn.Linear(hidden_dim, dim, bias=False)
        self.w3 = nn.Linear(dim, hidden_dim, bias=False)

    def forward(self, x):
        return self.w2(F.silu(self.w1(x)) * self.w3(x))


class ConvMLP(nn.Module):
    """SwiGLU ConvMLP (音频潜在用，1D卷积)"""
    def __init__(self, dim: int, hidden_dim: int, multiple_of: int = 256,
                 kernel_size: int = 3, padding: int = 1):
        super().__init__()
        hidden_dim = int(2 * hidden_dim / 3)
        hidden_dim = multiple_of * ((hidden_dim + multiple_of - 1) // multiple_of)
        self.w1 = ChannelLastConv1d(dim, hidden_dim, bias=False, kernel_size=kernel_size, padding=padding)
        self.w2 = ChannelLastConv1d(hidden_dim, dim, bias=False, kernel_size=kernel_size, padding=padding)
        self.w3 = ChannelLastConv1d(dim, hidden_dim, bias=False, kernel_size=kernel_size, padding=padding)

    def forward(self, x):
        return self.w2(F.silu(self.w1(x)) * self.w3(x))


# ============================================================
# AdaLN 调制
# ============================================================

def modulate(x: torch.Tensor, shift: torch.Tensor, scale: torch.Tensor) -> torch.Tensor:
    """自适应层归一化调制: x * (1 + scale) + shift"""
    return x * (1 + scale) + shift


# ============================================================
# 自注意力
# ============================================================

def attention(q: torch.Tensor, k: torch.Tensor, v: torch.Tensor) -> torch.Tensor:
    """缩放点积注意力 (使用 PyTorch 内置 SDPA)"""
    q = q.contiguous()
    k = k.contiguous()
    v = v.contiguous()
    out = F.scaled_dot_product_attention(q, k, v)
    out = rearrange(out, 'b h n d -> b n (h d)').contiguous()
    return out


class SelfAttention(nn.Module):
    """
    自注意力层，带 QK-Norm 和 RoPE。
    """
    def __init__(self, dim: int, nheads: int):
        super().__init__()
        self.dim = dim
        self.nheads = nheads
        self.qkv = nn.Linear(dim, dim * 3, bias=True)
        self.q_norm = RMSNorm(dim // nheads)
        self.k_norm = RMSNorm(dim // nheads)
        self.split_into_heads = Rearrange('b n (h d j) -> b h n d j', h=nheads, d=dim // nheads, j=3)

    def pre_attention(
        self, x: torch.Tensor, rot: Optional[torch.Tensor]
    ) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
        qkv = self.qkv(x)
        q, k, v = self.split_into_heads(qkv).chunk(3, dim=-1)
        q = q.squeeze(-1)
        k = k.squeeze(-1)
        v = v.squeeze(-1)
        q = self.q_norm(q)
        k = self.k_norm(k)
        if rot is not None:
            q = apply_rope(q, rot)
            k = apply_rope(k, rot)
        return q, k, v

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        q, k, v = self.pre_attention(x, None)
        out = attention(q, k, v)
        return out


# ============================================================
# MMDiT 单一块 (仅音频分支)
# ============================================================

class MMDitSingleBlock(nn.Module):
    """
    MMDiT 单一块，仅处理音频潜在。

    结构 (DiT-block 风格):
        x → LayerNorm → AdaLN调制 → Self-Attention → 门控残差
          → LayerNorm → AdaLN调制 → ConvMLP → 门控残差

    AdaLN 调制参数由全局条件 (时间步 + 文本全局语义) 生成。
    """
    def __init__(
        self,
        dim: int,
        nhead: int,
        mlp_ratio: float = 4.0,
        pre_only: bool = False,
        kernel_size: int = 7,
        padding: int = 3
    ):
        super().__init__()
        self.norm1 = nn.LayerNorm(dim, elementwise_affine=False)
        self.attn = SelfAttention(dim, nhead)

        self.pre_only = pre_only
        if pre_only:
            # pre_only: 只在注意力前做 AdaLN (用于文本分支的最后块)
            self.adaLN_modulation = nn.Sequential(nn.SiLU(), nn.Linear(dim, 2 * dim, bias=True))
        else:
            if kernel_size == 1:
                self.linear1 = nn.Linear(dim, dim)
            else:
                self.linear1 = ChannelLastConv1d(dim, dim, kernel_size=kernel_size, padding=padding)
            self.norm2 = nn.LayerNorm(dim, elementwise_affine=False)

            if kernel_size == 1:
                self.ffn = MLP(dim, int(dim * mlp_ratio))
            else:
                self.ffn = ConvMLP(dim, int(dim * mlp_ratio), kernel_size=kernel_size, padding=padding)

            # 6 个参数: shift_msa, scale_msa, gate_msa, shift_mlp, scale_mlp, gate_mlp
            self.adaLN_modulation = nn.Sequential(nn.SiLU(), nn.Linear(dim, 6 * dim, bias=True))

    def pre_attention(self, x: torch.Tensor, c: torch.Tensor, rot: Optional[torch.Tensor]):
        """前注意力: AdaLN 调制 + QKV 计算"""
        modulation = self.adaLN_modulation(c)
        if self.pre_only:
            (shift_msa, scale_msa) = modulation.chunk(2, dim=-1)
            gate_msa = shift_mlp = scale_mlp = gate_mlp = None
        else:
            (shift_msa, scale_msa, gate_msa, shift_mlp, scale_mlp,
             gate_mlp) = modulation.chunk(6, dim=-1)

        x = modulate(self.norm1(x), shift_msa, scale_msa)
        q, k, v = self.attn.pre_attention(x, rot)
        return (q, k, v), (gate_msa, shift_mlp, scale_mlp, gate_mlp)

    def post_attention(self, x: torch.Tensor, attn_out: torch.Tensor, c: tuple):
        """后注意力: 门控残差 + FFN"""
        if self.pre_only:
            return x

        (gate_msa, shift_mlp, scale_mlp, gate_mlp) = c
        x = x + self.linear1(attn_out) * gate_msa
        r = modulate(self.norm2(x), shift_mlp, scale_mlp)
        x = x + self.ffn(r) * gate_mlp
        return x

    def forward(self, x: torch.Tensor, cond: torch.Tensor, rot: Optional[torch.Tensor]) -> torch.Tensor:
        x_qkv, x_conditions = self.pre_attention(x, cond, rot)
        attn_out = attention(*x_qkv)
        x = self.post_attention(x, attn_out, x_conditions)
        return x


# ============================================================
# MMDiT 联合块 (音频 + 文本 联合注意力)
# ============================================================

class JointBlock_AT(nn.Module):
    """
    Audio + Text 联合块 (MMDiT 核心设计)。

    关键思想: 将音频潜在和文本嵌入沿序列维拼接，
    通过共享的自注意力层实现跨模态交互。

    流程:
        1. 音频分支: pre_attention (带 RoPE)
        2. 文本分支: pre_attention (无 RoPE)
        3. 拼接 Q/K/V → 联合自注意力
        4. 切分回音频/文本 → 各自 post_attention
    """
    def __init__(self, dim: int, nhead: int, mlp_ratio: float = 4.0, pre_only: bool = False):
        super().__init__()
        self.pre_only = pre_only
        # 音频分支 (kernel_size=3, ConvMLP)
        self.latent_block = MMDitSingleBlock(
            dim, nhead, mlp_ratio, pre_only=False, kernel_size=3, padding=1
        )
        # 文本分支 (kernel_size=1, Linear MLP)
        # 最后一个 joint block 的 text_block 通常为 pre_only
        self.text_block = MMDitSingleBlock(dim, nhead, mlp_ratio, pre_only=pre_only, kernel_size=1)

    def forward(
        self,
        latent: torch.Tensor,
        text_f: torch.Tensor,
        global_c: torch.Tensor,
        extended_c: torch.Tensor,
        latent_rot: Optional[torch.Tensor]
    ) -> tuple[torch.Tensor, torch.Tensor]:
        """
        Args:
            latent: [B, N_latent, D] 音频潜在
            text_f: [B, N_text, D] 文本嵌入 (ALM 输出投影后)
            global_c: [B, 1, D] 全局条件 (用于文本分支 AdaLN)
            extended_c: [B, 1, D] 扩展条件 (用于音频分支 AdaLN)
            latent_rot: RoPE 旋转矩阵

        Returns:
            latent, text_f: 更新后的音频潜在和文本嵌入
        """
        # 分别 pre_attention
        x_qkv, x_mod = self.latent_block.pre_attention(latent, extended_c, latent_rot)
        t_qkv, t_mod = self.text_block.pre_attention(text_f, global_c, rot=None)

        latent_len = latent.shape[1]
        text_len = text_f.shape[1]

        # 拼接 Q/K/V (沿 token 维)
        joint_qkv = [torch.cat([x_qkv[i], t_qkv[i]], dim=2) for i in range(3)]

        # 联合自注意力
        attn_out = attention(*joint_qkv)  # [B, latent_len + text_len, D]

        # 切回两段
        x_attn_out = attn_out[:, :latent_len]
        t_attn_out = attn_out[:, latent_len:]

        # 各自 post_attention
        latent = self.latent_block.post_attention(latent, x_attn_out, x_mod)
        if not self.pre_only:
            text_f = self.text_block.post_attention(text_f, t_attn_out, t_mod)

        return latent, text_f


# ============================================================
# 最终输出块
# ============================================================

class FinalBlock(nn.Module):
    """输出块: AdaLN + LayerNorm + Conv1d"""
    def __init__(self, dim: int, out_dim: int):
        super().__init__()
        self.adaLN_modulation = nn.Sequential(nn.SiLU(), nn.Linear(dim, 2 * dim, bias=True))
        self.norm = nn.LayerNorm(dim, elementwise_affine=False)
        self.conv = ChannelLastConv1d(dim, out_dim, kernel_size=7, padding=3)

    def forward(self, latent: torch.Tensor, c: torch.Tensor) -> torch.Tensor:
        shift, scale = self.adaLN_modulation(c).chunk(2, dim=-1)
        latent = modulate(self.norm(latent), shift, scale)
        latent = self.conv(latent)
        return latent


# ============================================================
# MMDiT 主模型 (MMAudio)
# ============================================================

@dataclass
class PreprocessedConditions:
    text_f: torch.Tensor       # [B, N_text, D]  投影后的文本序列
    text_f_c: torch.Tensor     # [B, D]          文本全局池化


class MMAudio(nn.Module):
    """
    MMEDIT 的 MMDiT 主干 (修改自 SD3 的 MMDiT)。

    输入:
        x: 噪声潜在 [B, latent_dim, T_lat]
        timesteps: 时间步 [B]
        context: ALM 输出 [B, N_text, text_dim]  (全局语义条件)
        time_aligned_context: 源音频VAE潜在 [B, T_lat, ta_context_dim]  (时间对齐条件)

    结构:
        audio_input_proj: 输入投影 (latent_dim*2 → hidden_dim)
            ↑ 因为 x + time_aligned_context 沿通道拼接
        text_input_proj: 文本投影 (text_dim → hidden_dim)
        text_cond_proj + global_cond_mlp: 全局条件投影
        t_embed: 时间步嵌入
        joint_blocks: N_joint 个联合注意力块
        fused_blocks: N_single 个单一块
        final_layer: 输出块

    典型配置 (small_16k):
        latent_dim=128, text_dim=1024, hidden_dim=1024
        depth=12 (joint), fused_depth=8 (single)
        num_heads=16, latent_seq_len=500
    """
    def __init__(
        self,
        *,
        latent_dim: int,
        text_dim: int,
        hidden_dim: int,
        depth: int,
        fused_depth: int,
        num_heads: int,
        mlp_ratio: float = 4.0,
        latent_seq_len: int,
        text_seq_len: int = 640,
        ta_context_dim: int,
        ta_context_fusion: str = 'add',
        ta_context_norm: bool = False,
        empty_string_feat: Optional[torch.Tensor] = None,
        v2: bool = False,
    ) -> None:
        super().__init__()

        self.v2 = v2
        self.latent_dim = latent_dim
        self._latent_seq_len = latent_seq_len
        self._text_seq_len = text_seq_len
        self.hidden_dim = hidden_dim
        self.num_heads = num_heads

        # --- time_aligned_context 投影 ---
        self.ta_context_fusion = ta_context_fusion
        self.ta_context_norm_flag = ta_context_norm

        if self.ta_context_fusion == "add":
            self.ta_context_projection = nn.Linear(ta_context_dim, hidden_dim, bias=False)
            self.ta_context_norm = nn.LayerNorm(ta_context_dim) if self.ta_context_norm_flag else nn.Identity()
        elif self.ta_context_fusion == "concat":
            self.ta_context_projection = nn.Identity()
            self.ta_context_norm = nn.Identity()
        else:
            raise ValueError(f"Unknown ta_context_fusion type: {ta_context_fusion}")

        # --- 输入投影 ---
        # 注意: latent_dim * 2 因为 x (噪声潜在) + time_aligned_context 拼接
        self.audio_input_proj = nn.Sequential(
            ChannelLastConv1d(latent_dim * 2, hidden_dim, kernel_size=7, padding=3),
            nn.SELU(),
            ConvMLP(hidden_dim, hidden_dim * 4, kernel_size=7, padding=3),
        )
        self.text_input_proj = nn.Sequential(
            nn.Linear(text_dim, hidden_dim),
            MLP(hidden_dim, hidden_dim * 4),
        )

        # 全局条件
        self.text_cond_proj = nn.Linear(hidden_dim, hidden_dim)
        self.global_cond_mlp = MLP(hidden_dim, hidden_dim * 4)

        # 时间步嵌入
        self.t_embed = TimestepEmbedder(hidden_dim, frequency_embedding_size=256, max_period=10000)

        # --- Transformer Blocks ---
        # 联合块: 音频 + 文本 联合注意力
        self.joint_blocks = nn.ModuleList([
            JointBlock_AT(hidden_dim, num_heads, mlp_ratio=mlp_ratio,
                          pre_only=(i == depth - fused_depth - 1))
            for i in range(depth - fused_depth)
        ])
        # 单一块: 仅音频自注意力 (细化连贯性)
        self.fused_blocks = nn.ModuleList([
            MMDitSingleBlock(hidden_dim, num_heads, mlp_ratio=mlp_ratio, kernel_size=3, padding=1)
            for _ in range(fused_depth)
        ])

        # 输出层
        self.final_layer = FinalBlock(hidden_dim, latent_dim)

        if empty_string_feat is None:
            empty_string_feat = torch.zeros((text_seq_len, text_dim))
        self.empty_string_feat = nn.Parameter(empty_string_feat, requires_grad=False)

        self.initialize_weights()
        self.initialize_rotations()

    def initialize_rotations(self):
        """初始化 RoPE 旋转矩阵"""
        base_freq = 1.0
        latent_rot = compute_rope_rotations(
            self._latent_seq_len,
            self.hidden_dim // self.num_heads,
            10000,
            freq_scaling=base_freq,
            device="cuda" if torch.cuda.is_available() else "cpu"
        )
        self.register_buffer('latent_rot', latent_rot, persistent=False)

    def update_seq_lengths(self, latent_seq_len: int, clip_seq_len: int, sync_seq_len: int) -> None:
        self._latent_seq_len = latent_seq_len
        self.initialize_rotations()

    def initialize_weights(self):
        """DiT 风格的权重初始化"""
        def _basic_init(module):
            if isinstance(module, nn.Linear):
                torch.nn.init.xavier_uniform_(module.weight)
                if module.bias is not None:
                    nn.init.constant_(module.bias, 0)

        self.apply(_basic_init)

        # Timestep embedding MLP
        nn.init.normal_(self.t_embed.mlp[0].weight, std=0.02)
        nn.init.normal_(self.t_embed.mlp[2].weight, std=0.02)

        # Zero-out AdaLN 调制层 (零初始化)
        for block in self.joint_blocks:
            nn.init.constant_(block.latent_block.adaLN_modulation[-1].weight, 0)
            nn.init.constant_(block.latent_block.adaLN_modulation[-1].bias, 0)
            nn.init.constant_(block.text_block.adaLN_modulation[-1].weight, 0)
            nn.init.constant_(block.text_block.adaLN_modulation[-1].bias, 0)
        for block in self.fused_blocks:
            nn.init.constant_(block.adaLN_modulation[-1].weight, 0)
            nn.init.constant_(block.adaLN_modulation[-1].bias, 0)

        # Zero-out 输出层
        nn.init.constant_(self.final_layer.adaLN_modulation[-1].weight, 0)
        nn.init.constant_(self.final_layer.adaLN_modulation[-1].bias, 0)
        nn.init.constant_(self.final_layer.conv.weight, 0)
        nn.init.constant_(self.final_layer.conv.bias, 0)

    def preprocess_conditions(self, text_f: torch.Tensor) -> PreprocessedConditions:
        """预处理文本条件: 投影 + 全局池化"""
        bs = text_f.shape[0]
        text_f = self.text_input_proj(text_f)
        text_f_c = self.text_cond_proj(text_f.mean(dim=1))  # 全局池化
        return PreprocessedConditions(text_f=text_f, text_f_c=text_f_c)

    def predict_flow(
        self,
        x: torch.Tensor,
        timesteps: torch.Tensor,
        conditions: PreprocessedConditions,
        time_aligned_context: torch.Tensor
    ) -> torch.Tensor:
        """
        核心预测流程。

        Args:
            x: 噪声潜在 [B, N_lat, latent_dim]  (channel-last)
            timesteps: 时间步 [B]
            conditions: 预处理后的文本条件
            time_aligned_context: 时间对齐条件 [B, N_lat, ta_dim]

        Returns:
            flow: 预测的速度 [B, N_lat, latent_dim]
        """
        assert x.shape[1] == self._latent_seq_len, f'{x.shape=} {self._latent_seq_len=}'

        text_f = conditions.text_f       # [B, N_text, D]
        text_f_c = conditions.text_f_c   # [B, D]

        timesteps = timesteps.to(x.dtype)

        # 1. 全局条件: 文本全局语义 + 时间步
        global_c = self.global_cond_mlp(text_f_c)            # [B, D]
        global_c = self.t_embed(timesteps).unsqueeze(1) + global_c.unsqueeze(1)  # [B, 1, D]
        extended_c = global_c  # 作为 AdaLN 的条件

        # 2. 时间对齐条件: 噪声潜在 + 源音频VAE潜在 沿通道拼接
        #    x: [B, N_lat, latent_dim], time_aligned_context: [B, N_lat, ta_dim]
        x = torch.cat([x, time_aligned_context], dim=-1)  # [B, N_lat, latent_dim + ta_dim]
        latent = self.audio_input_proj(x)  # [B, N_lat, hidden_dim]

        # 3. 联合注意力块 (音频 + 文本)
        for block in self.joint_blocks:
            latent, text_f = block(latent, text_f, global_c, extended_c, self.latent_rot)

        # 4. 单一块 (仅音频，细化)
        for block in self.fused_blocks:
            latent = block(latent, extended_c, self.latent_rot)

        # 5. 输出层
        flow = self.final_layer(latent, global_c)
        return flow

    def forward(
        self,
        x: torch.Tensor,
        timesteps: torch.Tensor,
        context: torch.Tensor,
        time_aligned_context: torch.Tensor,
        x_mask=None,
        context_mask=None,
    ) -> torch.Tensor:
        """
        模型主入口。

        Args:
            x: 噪声潜在 [B, latent_dim, T_lat]  (channel-first, 原始扩散格式)
            timesteps: 时间步 [B]
            context: ALM 输出 [B, N_text, text_dim]
            time_aligned_context: 源音频VAE潜在 [B, T_lat, ta_dim]
            x_mask: 潜在掩码 [B, T_lat]
            context_mask: 文本掩码 [B, N_text]

        Returns:
            flow: 预测速度 [B, latent_dim, T_lat]  (channel-first)
        """
        if timesteps.dim() == 0:
            timesteps = timesteps.expand(x.shape[0]).to(x.device, dtype=torch.long)

        # x: [B, C, T] → [B, T, C]
        x = x.transpose(1, 2)

        text_conditions = self.preprocess_conditions(context)
        flow = self.predict_flow(x, timesteps, text_conditions, time_aligned_context)

        # [B, T, C] → [B, C, T]
        flow = flow.transpose(1, 2)
        return flow


# ============================================================
# DDPM 扩散混合类
# ============================================================

class DiffusionMixin:
    """
    DDPM 扩散过程 Mixin。

    核心公式:
        前向过程: z_t = sqrt(ᾱ_t) * z_0 + sqrt(1 - ᾱ_t) * ε
        预测目标: 速度 v = sqrt(ᾱ_t) * ε - sqrt(1 - ᾱ_t) * z_0

    使用 diffusers 的 DDPMScheduler 管理噪声调度。
    """
    def __init__(
        self,
        noise_scheduler_name: str = "stabilityai/stable-diffusion-2-1",
        snr_gamma: float = None,
        cfg_drop_ratio: float = 0.2
    ) -> None:
        self.noise_scheduler_name = noise_scheduler_name
        self.snr_gamma = snr_gamma
        self.classifier_free_guidance = cfg_drop_ratio > 0.0
        self.cfg_drop_ratio = cfg_drop_ratio
        self.noise_scheduler = noise_schedulers.DDPMScheduler.from_pretrained(
            self.noise_scheduler_name, subfolder="scheduler"
        )

    def compute_snr(self, timesteps: torch.Tensor) -> torch.Tensor:
        """计算信噪比 SNR = (α/σ)²"""
        alphas_cumprod = self.noise_scheduler.alphas_cumprod
        sqrt_alphas_cumprod = alphas_cumprod ** 0.5
        sqrt_one_minus_alphas_cumprod = (1.0 - alphas_cumprod) ** 0.5

        sqrt_alphas_cumprod = sqrt_alphas_cumprod.to(device=timesteps.device)[timesteps].float()
        while len(sqrt_alphas_cumprod.shape) < len(timesteps.shape):
            sqrt_alphas_cumprod = sqrt_alphas_cumprod[..., None]
        alpha = sqrt_alphas_cumprod.expand(timesteps.shape)

        sqrt_one_minus_alphas_cumprod = sqrt_one_minus_alphas_cumprod.to(
            device=timesteps.device
        )[timesteps].float()
        while len(sqrt_one_minus_alphas_cumprod.shape) < len(timesteps.shape):
            sqrt_one_minus_alphas_cumprod = sqrt_one_minus_alphas_cumprod[..., None]
        sigma = sqrt_one_minus_alphas_cumprod.expand(timesteps.shape)

        snr = (alpha / sigma) ** 2
        return snr

    def get_timesteps(
        self,
        batch_size: int,
        device: torch.device,
        training: bool = True
    ) -> torch.Tensor:
        """采样时间步"""
        if training:
            timesteps = torch.randint(
                0,
                self.noise_scheduler.config.num_train_timesteps,
                (batch_size,),
                device=device
            )
        else:
            # 验证时用中间步
            timesteps = (self.noise_scheduler.config.num_train_timesteps // 2) * torch.ones(
                (batch_size,), dtype=torch.int64, device=device
            )
        timesteps = timesteps.long()
        return timesteps

    def get_input_target_and_timesteps(
        self,
        latent: torch.Tensor,
        training: bool,
    ):
        """
        生成带噪潜在、目标和时间步。

        核心 DDPM 前向过程:
            z_t = scheduler.add_noise(z_0, ε, t)
                = sqrt(ᾱ_t) * z_0 + sqrt(1 - ᾱ_t) * ε

        目标 (速度预测):
            v = scheduler.get_velocity(z_0, ε, t)
              = sqrt(ᾱ_t) * ε - sqrt(1 - ᾱ_t) * z_0
        """
        batch_size = latent.shape[0]
        device = latent.device
        num_train_timesteps = self.noise_scheduler.config.num_train_timesteps
        self.noise_scheduler.set_timesteps(num_train_timesteps, device=device)
        timesteps = self.get_timesteps(batch_size, device, training=training)
        noise = torch.randn_like(latent)
        noisy_latent = self.noise_scheduler.add_noise(latent, noise, timesteps)
        target = self.get_target(latent, noise, timesteps)
        return noisy_latent, target, timesteps

    def get_target(
        self, latent: torch.Tensor, noise: torch.Tensor, timesteps: torch.Tensor
    ) -> torch.Tensor:
        """根据 prediction_type 获取训练目标"""
        if self.noise_scheduler.config.prediction_type == "epsilon":
            target = noise
        elif self.noise_scheduler.config.prediction_type == "v_prediction":
            target = self.noise_scheduler.get_velocity(latent, noise, timesteps)
        else:
            raise ValueError(
                f"Unknown prediction type {self.noise_scheduler.config.prediction_type}"
            )
        return target

    def loss_with_snr(
        self,
        pred: torch.Tensor,
        target: torch.Tensor,
        timesteps: torch.Tensor,
        mask: torch.Tensor,
        reduce: bool = True
    ) -> torch.Tensor:
        """
        计算 MSE 损失，可选 SNR 加权 (Min-SNR)。

        Min-SNR 加权: loss_weight = min(SNR, γ) / SNR
        参考: https://arxiv.org/abs/2303.09556
        """
        if self.snr_gamma is None:
            loss = F.mse_loss(pred.float(), target.float(), reduction="none")
            loss = loss_with_mask(loss, mask, reduce=reduce)
        else:
            snr = self.compute_snr(timesteps)
            mse_loss_weights = torch.stack(
                [snr, self.snr_gamma * torch.ones_like(timesteps)], dim=1,
            ).min(dim=1)[0]
            mse_loss_weights = mse_loss_weights / snr
            loss = F.mse_loss(pred.float(), target.float(), reduction="none")
            loss = loss_with_mask(loss, mask, reduce=False) * mse_loss_weights
            if reduce:
                loss = loss.mean()
        return loss

    def rescale_cfg(
        self, pred_cond: torch.Tensor, pred_cfg: torch.Tensor, guidance_rescale: float
    ):
        """CFG rescale (Common Diffusion Noise Schedules and Sample Steps are Flawed)"""
        std_cond = pred_cond.std(dim=list(range(1, pred_cond.ndim)), keepdim=True)
        std_cfg = pred_cfg.std(dim=list(range(1, pred_cfg.ndim)), keepdim=True)
        pred_rescaled = pred_cfg * (std_cond / std_cfg)
        pred_cfg = guidance_rescale * pred_rescaled + (1 - guidance_rescale) * pred_cfg
        return pred_cfg


# ============================================================
# 完整扩散模型 (Diffusion + Autoencoder + Content Encoder)
# ============================================================

class SingleTaskCrossAttentionAudioDiffusion(DiffusionMixin):
    """
    MMEDIT 完整扩散模型 (audio editing 任务)。

    组成:
        autoencoder: StableVAE (冻结)
        content_encoder: ContentEncoder (ALM + VAE projector, ALM冻结)
        backbone: MMAudio (MMDiT, 可训练)

    训练流程:
        1. 目标波形 → VAE encoder → z_0
        2. 内容 (caption + 源音频) → content_encoder → 全局语义 + 时间对齐条件
        3. DDPM 加噪: z_t = add_noise(z_0, ε, t)
        4. CFG dropout: 随机丢弃文本条件 (训练无条件生成)
        5. MMDiT 预测: v̂ = backbone(z_t, t, context, time_aligned_context)
        6. 损失: MSE(v̂, v_target)

    推理流程:
        1. 源音频 + 指令 → content_encoder → 条件
        2. 从纯噪声开始
        3. DDIM/DDPM 迭代去噪
        4. VAE decoder → 波形
    """
    def __init__(
        self,
        autoencoder,  # AutoEncoderBase
        content_encoder,  # ContentEncoder
        backbone: nn.Module,  # MMAudio
        content_dim: int,
        noise_scheduler_name: str = "stabilityai/stable-diffusion-2-1",
        snr_gamma: float = None,
        cfg_drop_ratio: float = 0.2,
    ):
        nn.Module.__init__(self)
        DiffusionMixin.__init__(
            self, noise_scheduler_name, snr_gamma, cfg_drop_ratio
        )
        self.autoencoder = autoencoder
        for param in self.autoencoder.parameters():
            param.requires_grad = False

        self.content_encoder = content_encoder
        self.backbone = backbone
        self.dummy_param = nn.Parameter(torch.empty(0))

    def forward(
        self,
        content: list[Any],
        task: list[str],
        waveform: torch.Tensor,
        waveform_lengths: torch.Tensor,
        **kwargs
    ):
        """
        训练前向传播。

        Args:
            content: [{"audio": waveform, "caption": str}, ...]
            task: ["audio_editing", ...]
            waveform: 目标波形 [B, T_wave]
            waveform_lengths: [B]

        Returns:
            loss: 标量损失
        """
        device = self.dummy_param.device

        # 1. 目标波形 → VAE 潜在空间
        self.autoencoder.eval()
        self.content_encoder.eval()
        with torch.no_grad():
            latent, latent_mask = self.autoencoder.encode(
                waveform.unsqueeze(1), waveform_lengths, pad_latent_len=500
            )

        # 2. 编码内容 (ALM + VAE projector)
        with torch.no_grad():
            content_dict = self.content_encoder.encode_content(content, task, device)
        context, context_mask = content_dict["content"], content_dict["content_mask"]
        time_aligned_content = content_dict["length_aligned_content"]
        time_aligned_content_mask = content_dict["time_aligned_content_mask"]
        latent_mask = time_aligned_content_mask.to(device)

        # 3. CFG dropout: 随机丢弃文本条件 (用于训练无条件生成)
        if self.training and self.classifier_free_guidance:
            mask_indices = [
                k for k in range(len(waveform))
                if random.random() < self.cfg_drop_ratio
            ]
            if len(mask_indices) > 0:
                context[mask_indices] = 0
                # 注意: time_aligned_content 不被丢弃 (保留源音频参考)

        # 4. DDPM 加噪
        noisy_latent, target, timesteps = self.get_input_target_and_timesteps(
            latent, self.training
        )

        # 5. MMDiT 预测速度
        pred = self.backbone(
            x=noisy_latent,
            timesteps=timesteps,
            time_aligned_context=time_aligned_content,
            context=context,
            x_mask=latent_mask,
            context_mask=context_mask
        )

        pred = pred.transpose(1, self.autoencoder.time_dim)
        target = target.transpose(1, self.autoencoder.time_dim)
        loss = self.loss_with_snr(pred, target, timesteps, latent_mask)

        return loss

    def prepare_latent(
        self, batch_size: int, scheduler: SchedulerMixin,
        latent_shape: Sequence[int], dtype: torch.dtype, device: str
    ):
        """准备初始噪声潜在"""
        shape = (batch_size, *latent_shape)
        latent = randn_tensor(shape, generator=None, device=device, dtype=dtype)
        latent = latent * scheduler.init_noise_sigma
        return latent

    def iterative_denoise(
        self,
        latent: torch.Tensor,
        scheduler: SchedulerMixin,
        verbose: bool,
        cfg: bool,
        cfg_scale: float,
        cfg_rescale: float,
        backbone_input: dict,
    ):
        """
        迭代去噪采样。

        对于 DDPM: x_{t-1} = scheduler.step(ε_pred, t, x_t).prev_sample
        对于 DDIM: 确定性一步更新
        """
        timesteps = scheduler.timesteps
        num_steps = len(timesteps)
        num_warmup_steps = len(timesteps) - num_steps * scheduler.order
        progress_bar = tqdm(range(num_steps), disable=not verbose)

        for i, timestep in enumerate(timesteps):
            # CFG: 拼接条件和无条件
            if cfg:
                latent_input = torch.cat([latent, latent])
            else:
                latent_input = latent
            latent_input = scheduler.scale_model_input(latent_input, timestep)

            noise_pred = self.backbone(
                x=latent_input, timesteps=timestep, **backbone_input
            )

            # CFG 引导
            if cfg:
                noise_pred_uncond, noise_pred_content = noise_pred.chunk(2)
                noise_pred = noise_pred_uncond + cfg_scale * (
                    noise_pred_content - noise_pred_uncond
                )
                if cfg_rescale != 0.0:
                    noise_pred = self.rescale_cfg(
                        noise_pred_content, noise_pred, cfg_rescale
                    )

            # 一步去噪
            latent = scheduler.step(noise_pred, timestep, latent).prev_sample

            if i == len(timesteps) - 1 or ((i + 1) > num_warmup_steps and
                                           (i + 1) % scheduler.order == 0):
                progress_bar.update(1)

        progress_bar.close()
        return latent

    @torch.no_grad()
    def inference(
        self,
        content: list[Any],
        task: list[str],
        scheduler: SchedulerMixin,
        num_steps: int = 50,
        guidance_scale: float = 3.0,
        guidance_rescale: float = 0.0,
        disable_progress: bool = True,
        mask_time_aligned_content: bool = True,
        **kwargs
    ):
        """
        推理: 从噪声生成编辑后的音频。

        Args:
            content: 源音频 + 指令
            task: 任务类型
            scheduler: 去噪调度器 (DDIM / DDPM)
            num_steps: 采样步数
            guidance_scale: CFG 引导强度
            guidance_rescale: CFG rescale
            mask_time_aligned_content: 是否在无条件分支中掩码时间对齐内容
                - True: 无条件分支丢弃源音频参考 (纯生成)
                - False: 无条件分支保留源音频参考 (推荐用于编辑)

        Returns:
            waveform: 生成的波形 [B, C, T]
        """
        device = self.dummy_param.device
        classifier_free_guidance = guidance_scale > 1.0
        batch_size = len(content)

        # 1. 编码内容
        content_dict = self.content_encoder.encode_content(content, task, device)
        context, context_mask = content_dict["content"], content_dict["content_mask"]
        time_aligned_content = content_dict["length_aligned_content"]
        time_aligned_content_mask = content_dict["time_aligned_content_mask"]

        B, T, C = time_aligned_content.shape
        latent_shape = (C, T)
        latent_mask = time_aligned_content_mask.to(device)

        # 2. 准备 CFG 的无条件分支
        if classifier_free_guidance:
            if mask_time_aligned_content:
                uncond_time_aligned_content = torch.zeros_like(time_aligned_content)
            else:
                uncond_time_aligned_content = time_aligned_content.detach().clone()

            uncond_context = torch.zeros_like(context)
            uncond_context_mask = context_mask.detach().clone()
            time_aligned_content = torch.cat([
                uncond_time_aligned_content, time_aligned_content
            ])
            context = torch.cat([uncond_context, context])
            context_mask = torch.cat([uncond_context_mask, context_mask])
            latent_mask = torch.cat([
                latent_mask, latent_mask.detach().clone()
            ])

        # 3. 设置调度器并准备初始噪声
        scheduler.set_timesteps(num_steps, device=device)
        latent = self.prepare_latent(
            batch_size, scheduler, latent_shape, context.dtype, device
        )

        # 4. 迭代去噪
        latent = self.iterative_denoise(
            latent=latent,
            scheduler=scheduler,
            verbose=not disable_progress,
            cfg=classifier_free_guidance,
            cfg_scale=guidance_scale,
            cfg_rescale=guidance_rescale,
            backbone_input={
                "x_mask": latent_mask,
                "context": context,
                "context_mask": context_mask,
                "time_aligned_context": time_aligned_content,
            }
        )

        # 5. VAE 解码
        waveform = self.autoencoder.decode(latent, latent_mask)
        return waveform


# ============================================================
# 预设模型配置
# ============================================================

def small_16k(**kwargs) -> MMAudio:
    """
    小型 MMDiT 配置 (约对应论文中的基础配置)。
    latent_dim=128, hidden_dim=1024, 12层joint + 8层single, 16头
    """
    num_heads = 16
    return MMAudio(
        latent_dim=128,
        text_dim=1024,
        hidden_dim=64 * num_heads,  # 1024
        depth=12,
        fused_depth=8,
        num_heads=num_heads,
        latent_seq_len=500,
        **kwargs
    )


# ============================================================
# DDPM 数学底层总结
# ============================================================
"""
DDPM (Denoising Diffusion Probabilistic Models) 数学原理:

## 前向过程 (加噪)
    q(z_t | z_0) = N(z_t; sqrt(ᾱ_t) * z_0, (1 - ᾱ_t) * I)
    z_t = sqrt(ᾱ_t) * z_0 + sqrt(1 - ᾱ_t) * ε,   ε ~ N(0, I)

    其中:
        α_t = 1 - β_t          (信号保留率)
        ᾱ_t = ∏_{s=1}^t α_s    (累积信号保留率)
        β_t 随 t 增大 (噪声增加)

## 逆向过程 (去噪)
    p_θ(z_{t-1} | z_t) = N(z_{t-1}; μ_θ(z_t, t), Σ_θ(z_t, t))

## 预测目标
    1. 噪声预测 (epsilon): 预测 ε
       L_simple = E_{t,z_0,ε}[||ε - ε_θ(z_t, t)||²]

    2. 速度预测 (v_prediction) [MMEDIT 使用]:
       v = sqrt(ᾱ_t) * ε - sqrt(1 - ᾱ_t) * z_0
       L = E[||v - v_θ(z_t, t)||²]

       优势: 速度预测在不同噪声水平下更稳定，
             且与流匹配 (Flow Matching) 有理论联系。

## 代码对应
    加噪:  noise_scheduler.add_noise(latent, noise, timesteps)
           内部实现: z_t = sqrt(ᾱ_t) * z_0 + sqrt(1 - ᾱ_t) * ε

    目标:  noise_scheduler.get_velocity(latent, noise, timesteps)
           内部实现: v = sqrt(ᾱ_t) * ε - sqrt(1 - ᾱ_t) * z_0

    去噪:  scheduler.step(noise_pred, timestep, latent).prev_sample
           根据预测结果计算 x_{t-1}

    损失:  MSE(pred, target)  [可选 Min-SNR 加权]

## ALM 条件注入路径
    路径 1 (全局 AdaLN):
        H (ALM输出) → AvgPool → text_cond_proj → global_cond_mlp
        + t_embed (时间步嵌入)
        → 每个 block 的 adaLN_modulation (生成 shift/scale/gate)

    路径 2 (联合注意力):
        H → text_input_proj → text_f
        与音频 latent 拼接 → 联合自注意力 → 事件级定位

    路径 3 (时间对齐拼接):
        z_in (源音频VAE潜在) → projector → time_aligned_context
        与 z_t (噪声潜在) 沿通道拼接 → audio_input_proj
        提供未编辑区域的参考，保证一致性
"""
