# Generated by Trae Work
"""
MMEDIT VAE (StableVAE) - 波形变分自编码器

基于 Oobleck 架构的 1D 卷积 VAE，直接在波形域操作。
下采样率 480x，24kHz 采样率 → 50Hz 潜在帧率。

参考文件:
- models/autoencoder/waveform/stable_vae.py
- models/autoencoder/autoencoder_base.py
"""

import math
from typing import Any, Literal, Callable
from pathlib import Path
from abc import abstractmethod, ABC
from typing import Sequence

import torch
import torch.nn as nn
from torch.nn.utils import weight_norm
import torchaudio
from alias_free_torch import Activation1d


# ============================================================
# 基类
# ============================================================

class AutoEncoderBase(ABC):
    def __init__(
        self, downsampling_ratio: int, sample_rate: int,
        latent_shape: Sequence[int | None]
    ):
        self.downsampling_ratio = downsampling_ratio
        self.sample_rate = sample_rate
        self.latent_token_rate = sample_rate // downsampling_ratio
        self.latent_shape = latent_shape
        self.time_dim = latent_shape.index(None) + 1  # the first dim is batch

    @abstractmethod
    def encode(
        self, waveform: torch.Tensor, waveform_lengths: torch.Tensor
    ) -> tuple[torch.Tensor, torch.Tensor]:
        ...


# ============================================================
# 工具函数与激活
# ============================================================

# jit script make it 1.4x faster and save GPU memory
@torch.jit.script
def snake_beta(x, alpha, beta):
    return x + (1.0 / (beta + 0.000000001)) * pow(torch.sin(x * alpha), 2)


class SnakeBeta(nn.Module):
    def __init__(
        self,
        in_features,
        alpha=1.0,
        alpha_trainable=True,
        alpha_logscale=True
    ):
        super(SnakeBeta, self).__init__()
        self.in_features = in_features

        self.alpha_logscale = alpha_logscale
        if self.alpha_logscale:
            self.alpha = nn.Parameter(torch.zeros(in_features) * alpha)
            self.beta = nn.Parameter(torch.zeros(in_features) * alpha)
        else:
            self.alpha = nn.Parameter(torch.ones(in_features) * alpha)
            self.beta = nn.Parameter(torch.ones(in_features) * alpha)

        self.alpha.requires_grad = alpha_trainable
        self.beta.requires_grad = alpha_trainable

    def forward(self, x):
        alpha = self.alpha.unsqueeze(0).unsqueeze(-1)
        beta = self.beta.unsqueeze(0).unsqueeze(-1)
        if self.alpha_logscale:
            alpha = torch.exp(alpha)
            beta = torch.exp(beta)
        x = snake_beta(x, alpha, beta)
        return x


def WNConv1d(*args, **kwargs):
    return weight_norm(nn.Conv1d(*args, **kwargs))


def WNConvTranspose1d(*args, **kwargs):
    return weight_norm(nn.ConvTranspose1d(*args, **kwargs))


def get_activation(
    activation: Literal["elu", "snake", "none"],
    antialias=False,
    channels=None
) -> nn.Module:
    if activation == "elu":
        act = nn.ELU()
    elif activation == "snake":
        act = SnakeBeta(channels)
    elif activation == "none":
        act = nn.Identity()
    else:
        raise ValueError(f"Unknown activation {activation}")

    if antialias:
        act = Activation1d(act)
    return act


# ============================================================
# 残差单元 & 编码器/解码器块
# ============================================================

class ResidualUnit(nn.Module):
    def __init__(
        self,
        in_channels,
        out_channels,
        dilation,
        use_snake=False,
        antialias_activation=False
    ):
        super().__init__()
        self.dilation = dilation
        padding = (dilation * (7 - 1)) // 2

        self.layers = nn.Sequential(
            get_activation(
                "snake" if use_snake else "elu",
                antialias=antialias_activation,
                channels=out_channels
            ),
            WNConv1d(
                in_channels=in_channels,
                out_channels=out_channels,
                kernel_size=7,
                dilation=dilation,
                padding=padding
            ),
            get_activation(
                "snake" if use_snake else "elu",
                antialias=antialias_activation,
                channels=out_channels
            ),
            WNConv1d(
                in_channels=out_channels,
                out_channels=out_channels,
                kernel_size=1
            )
        )

    def forward(self, x):
        res = x
        x = self.layers(x)
        return x + res


class EncoderBlock(nn.Module):
    def __init__(
        self,
        in_channels,
        out_channels,
        stride,
        use_snake=False,
        antialias_activation=False
    ):
        super().__init__()
        self.layers = nn.Sequential(
            ResidualUnit(in_channels, in_channels, dilation=1, use_snake=use_snake),
            ResidualUnit(in_channels, in_channels, dilation=3, use_snake=use_snake),
            ResidualUnit(in_channels, in_channels, dilation=9, use_snake=use_snake),
            get_activation("snake" if use_snake else "elu",
                           antialias=antialias_activation, channels=in_channels),
            WNConv1d(
                in_channels=in_channels,
                out_channels=out_channels,
                kernel_size=2 * stride,
                stride=stride,
                padding=math.ceil(stride / 2)
            ),
        )

    def forward(self, x):
        return self.layers(x)


class DecoderBlock(nn.Module):
    def __init__(
        self,
        in_channels,
        out_channels,
        stride,
        use_snake=False,
        antialias_activation=False,
        use_nearest_upsample=False
    ):
        super().__init__()

        if use_nearest_upsample:
            upsample_layer = nn.Sequential(
                nn.Upsample(scale_factor=stride, mode="nearest"),
                WNConv1d(
                    in_channels=in_channels,
                    out_channels=out_channels,
                    kernel_size=2 * stride,
                    stride=1,
                    bias=False,
                    padding='same'
                )
            )
        else:
            upsample_layer = WNConvTranspose1d(
                in_channels=in_channels,
                out_channels=out_channels,
                kernel_size=2 * stride,
                stride=stride,
                padding=math.ceil(stride / 2)
            )

        self.layers = nn.Sequential(
            get_activation("snake" if use_snake else "elu",
                           antialias=antialias_activation, channels=in_channels),
            upsample_layer,
            ResidualUnit(out_channels, out_channels, dilation=1, use_snake=use_snake),
            ResidualUnit(out_channels, out_channels, dilation=3, use_snake=use_snake),
            ResidualUnit(out_channels, out_channels, dilation=9, use_snake=use_snake),
        )

    def forward(self, x):
        return self.layers(x)


# ============================================================
# 编码器 / 解码器
# ============================================================

class OobleckEncoder(nn.Module):
    """
    Oobleck 风格 1D 卷积编码器。
    4 个下采样块，总 stride = 2*4*8*8 = 512 (可配置)
    """
    def __init__(
        self,
        in_channels=2,
        channels=128,
        latent_dim=32,
        c_mults=[1, 2, 4, 8],
        strides=[2, 4, 8, 8],
        use_snake=False,
        antialias_activation=False
    ):
        super().__init__()
        c_mults = [1] + c_mults
        self.depth = len(c_mults)

        layers = [
            WNConv1d(
                in_channels=in_channels,
                out_channels=c_mults[0] * channels,
                kernel_size=7,
                padding=3
            )
        ]

        for i in range(self.depth - 1):
            layers += [
                EncoderBlock(
                    in_channels=c_mults[i] * channels,
                    out_channels=c_mults[i + 1] * channels,
                    stride=strides[i],
                    use_snake=use_snake
                )
            ]

        layers += [
            get_activation("snake" if use_snake else "elu",
                           antialias=antialias_activation, channels=c_mults[-1] * channels),
            WNConv1d(
                in_channels=c_mults[-1] * channels,
                out_channels=latent_dim,
                kernel_size=3,
                padding=1
            )
        ]

        self.layers = nn.Sequential(*layers)

    def forward(self, x):
        return self.layers(x)


class OobleckDecoder(nn.Module):
    """
    Oobleck 风格 1D 卷积解码器。
    与编码器对称的上采样结构。
    """
    def __init__(
        self,
        out_channels=2,
        channels=128,
        latent_dim=32,
        c_mults=[1, 2, 4, 8],
        strides=[2, 4, 8, 8],
        use_snake=False,
        antialias_activation=False,
        use_nearest_upsample=False,
        final_tanh=True
    ):
        super().__init__()
        c_mults = [1] + c_mults
        self.depth = len(c_mults)

        layers = [
            WNConv1d(
                in_channels=latent_dim,
                out_channels=c_mults[-1] * channels,
                kernel_size=7,
                padding=3
            ),
        ]

        for i in range(self.depth - 1, 0, -1):
            layers += [
                DecoderBlock(
                    in_channels=c_mults[i] * channels,
                    out_channels=c_mults[i - 1] * channels,
                    stride=strides[i - 1],
                    use_snake=use_snake,
                    antialias_activation=antialias_activation,
                    use_nearest_upsample=use_nearest_upsample
                )
            ]

        layers += [
            get_activation("snake" if use_snake else "elu",
                           antialias=antialias_activation, channels=c_mults[0] * channels),
            WNConv1d(
                in_channels=c_mults[0] * channels,
                out_channels=out_channels,
                kernel_size=7,
                padding=3,
                bias=False
            ),
            nn.Tanh() if final_tanh else nn.Identity()
        ]

        self.layers = nn.Sequential(*layers)

    def forward(self, x):
        return self.layers(x)


# ============================================================
# VAE 瓶颈层
# ============================================================

class Bottleneck(nn.Module):
    def __init__(self, is_discrete: bool = False):
        super().__init__()
        self.is_discrete = is_discrete

    def encode(self, x, return_info=False, **kwargs):
        raise NotImplementedError

    def decode(self, x):
        raise NotImplementedError


@torch.jit.script
def vae_sample(mean, scale) -> dict[str, torch.Tensor]:
    """VAE 重参数化采样 + KL 散度计算"""
    stdev = nn.functional.softplus(scale) + 1e-4
    var = stdev * stdev
    logvar = torch.log(var)
    latents = torch.randn_like(mean) * stdev + mean
    kl = (mean * mean + var - logvar - 1).sum(1).mean()
    return {"latents": latents, "kl": kl}


class VAEBottleneck(Bottleneck):
    """
    连续 VAE 瓶颈。
    输入通道被拆分为 mean 和 scale 两部分。
    """
    def __init__(self):
        super().__init__(is_discrete=False)

    def encode(self, x, return_info=False, **kwargs):
        mean, scale = x.chunk(2, dim=1)
        sampled = vae_sample(mean, scale)
        if return_info:
            return sampled["latents"], {"kl": sampled["kl"]}
        else:
            return sampled["latents"]

    def decode(self, x):
        return x


# ============================================================
# 预变换基类
# ============================================================

class Pretransform(nn.Module):
    def __init__(self, enable_grad, io_channels, is_discrete):
        super().__init__()
        self.is_discrete = is_discrete
        self.io_channels = io_channels
        self.encoded_channels = None
        self.downsampling_ratio = None
        self.enable_grad = enable_grad

    def encode(self, x):
        raise NotImplementedError

    def decode(self, z):
        raise NotImplementedError


# ============================================================
# StableVAE 主类
# ============================================================

class StableVAE(AutoEncoderBase):
    """
    波形域变分自编码器。

    架构:
        输入波形 [B, 1, T_wave]
            ↓ Encoder (4个下采样块, stride 乘积=480)
        编码器输出 [B, 2*latent_dim, T_lat]  (mean + scale)
            ↓ VAEBottleneck (重参数化)
        潜在表示 z [B, latent_dim, T_lat]   ← 扩散模型在此操作
            ↓ Decoder (4个上采样块)
        重建波形 [B, 1, T_wave]

    典型配置 (24kHz, 下采样率480):
        - latent_dim: 128
        - 潜在帧率: 24000 / 480 = 50 Hz
        - strides: [2, 4, 5, 12]  或其他组合，乘积=480
    """
    def __init__(
        self,
        encoder: OobleckEncoder,
        decoder: OobleckDecoder,
        latent_dim: int,
        downsampling_ratio: int,
        sample_rate: int,
        io_channels: int = 2,
        bottleneck: Bottleneck = None,
        pretransform: Pretransform = None,
        in_channels: int = None,
        out_channels: int = None,
        soft_clip: bool = False,
    ):
        AutoEncoderBase.__init__(
            self,
            downsampling_ratio=downsampling_ratio,
            sample_rate=sample_rate,
            latent_shape=(latent_dim, None)
        )

        self.latent_dim = latent_dim
        self.io_channels = io_channels
        self.in_channels = io_channels
        self.out_channels = io_channels
        self.min_length = self.downsampling_ratio

        if in_channels is not None:
            self.in_channels = in_channels
        if out_channels is not None:
            self.out_channels = out_channels

        self.bottleneck = bottleneck
        self.encoder = encoder
        self.decoder = decoder
        self.pretransform = pretransform
        self.soft_clip = soft_clip
        self.is_discrete = self.bottleneck is not None and self.bottleneck.is_discrete

    def encode(
        self, waveform: torch.Tensor, waveform_lengths: torch.Tensor,
        pad_latent_len: int = 500
    ) -> tuple[torch.Tensor, torch.Tensor]:
        """
        将波形编码到潜在空间。

        Args:
            waveform: [B, C, T_wave] 波形
            waveform_lengths: [B] 每段波形的有效长度
            pad_latent_len: 填充到的潜在长度

        Returns:
            z: [B, latent_dim, pad_latent_len] 潜在表示
            z_mask: [B, pad_latent_len] 有效掩码 (1=有效, 0=填充)
        """
        z = self.encoder(waveform)
        z = self.bottleneck.encode(z)
        z_length = waveform_lengths // self.downsampling_ratio
        z_mask = create_mask_from_length(z_length, max_length=pad_latent_len)

        B, C, L = z.shape
        if L < pad_latent_len:
            pad_size = pad_latent_len - L
            z = torch.cat([z, torch.zeros(B, C, pad_size, device=z.device, dtype=z.dtype)], dim=-1)
        return z, z_mask

    def decode(self, latents: torch.Tensor, latent_mask: torch.Tensor | None = None) -> torch.Tensor:
        """
        将潜在表示解码回波形。

        Args:
            latents: [B, C, T_latent] 潜在表示
            latent_mask: [B, T_latent] 可选掩码，1=有效，0=padding

        Returns:
            waveform: [B, C, T_wave] 重建波形
        """
        if latent_mask is not None:
            outputs = []
            for b in range(latents.size(0)):
                valid_idx = latent_mask[b].bool()
                valid_latents = latents[b, :, valid_idx]  # [C, T_valid]
                outputs.append(self.decoder(valid_latents.unsqueeze(0)))
            return torch.cat(outputs, dim=0)
        else:
            return self.decoder(latents)


# ============================================================
# VAE 投影包装器 (用于 audio_encoder 路径)
# ============================================================

class StableVAEProjectorWrapper(nn.Module):
    """
    将 VAE 编码器输出投影到指定维度，作为 time_aligned_context。
    在 audio_editing 任务中，源音频的 VAE 潜在通过此包装器后
    与噪声潜在沿通道拼接，注入到 DiT 中。
    """
    def __init__(
        self,
        vae_dim: int,
        embed_dim: int,
        model: StableVAE | None = None,
    ):
        super().__init__()
        self.model = model
        self.proj = nn.Linear(vae_dim, embed_dim)

    def forward(
        self, waveform: torch.Tensor, waveform_lengths: torch.Tensor
    ) -> tuple[torch.Tensor, torch.Tensor]:
        self.model.eval()
        with torch.no_grad():
            z, z_mask = self.model.encode(waveform, waveform_lengths, pad_latent_len=500)
        z = self.proj(z.transpose(1, 2))  # [B, T, embed_dim]
        return {"output": z, "mask": z_mask}


# ============================================================
# 工具函数 (从 utils.torch_utilities 引入)
# ============================================================

def create_mask_from_length(lengths: torch.Tensor, max_length: int = None) -> torch.Tensor:
    """根据长度序列生成掩码 [B, max_len]"""
    if max_length is None:
        max_length = lengths.max().item()
    batch_size = lengths.shape[0]
    mask = torch.arange(max_length, device=lengths.device).unsqueeze(0).expand(batch_size, -1)
    mask = mask < lengths.unsqueeze(1)
    return mask.float()


# ============================================================
# 辅助：移除 state_dict 前缀
# ============================================================

def remove_key_prefix_factory(prefix: str):
    def remove_key_prefix(model_dict, state_dict):
        new_state_dict = {}
        for k, v in state_dict.items():
            if k.startswith(prefix):
                new_k = k[len(prefix):]
                if new_k in model_dict:
                    new_state_dict[new_k] = v
        return new_state_dict
    return remove_key_prefix
