# Generated by Trae Work
"""
UNISON MLLM 隐状态提取 + 深度融合 (Deep Fusion)

UNISON 的核心创新：利用 MLLM 的全部隐状态，通过深度融合注入 DiT。

两种 MLLM 后端:
1. Qwen2.5-Omni (Thinker 语言模型) - 多模态模型的语言部分
2. Qwen3 Causal LM - 纯文本因果语言模型

深度融合机制:
    - MLLM 有 N 层，DiT 有 M 层 (M ≤ N)
    - 从 MLLM 均匀采样 M 层的隐状态
    - 每个 DiT 块有一个独立的线性投影 (deep_fusion_proj[i])
    - 投影后的 MLLM 隐状态作为文本 token 注入对应 DiT 块的联合注意力

层次化对齐效果:
    - 早期 DiT 块 ← 浅层 LLM 表征 (词汇/音韵结构)
    - 后期 DiT 块 ← 深层 LLM 表征 (抽象语义)

参考文件:
- text_encoders/omni_encoder.py (Qwen2.5-Omni 版本)
- text_encoders/qwen3_causal_encoder.py (Qwen3 版本)
- transformers/backbone.py (deep_fusion_projs 在 UnisonBackbone 中)
"""

import gc
from typing import List, Optional

import numpy as np
import torch
import torch.nn as nn


# ============================================================
# 隐状态层索引采样策略
# ============================================================

def get_layer_indices(total_llm: int, dit_depth: int, mode: str = "interval") -> List[int]:
    """
    从 MLLM 层中均匀采样 DiT 块所需的层数。

    Args:
        total_llm: MLLM 总层数
        dit_depth: DiT 总块数 (double + single)
        mode: "interval" = 均匀间隔采样; "last" = 最后几层

    Returns:
        层索引列表 (1-indexed，对应 hidden_states 的索引)

    示例:
        total_llm=28, dit_depth=20, mode="interval"
        → 从 28 层中均匀选 20 层
    """
    available_indices = list(range(1, total_llm + 1))
    if total_llm >= dit_depth:
        if mode == "interval":
            idx_array = np.linspace(0, len(available_indices) - 1, dit_depth, dtype=int)
            selected_indices = [available_indices[i] for i in idx_array]
        else:
            selected_indices = available_indices[-dit_depth:]
    else:
        # MLLM 层数少于 DiT 块数：重复最后一层填充
        selected_indices = available_indices[:]
        selected_indices.extend([available_indices[-1]] * (dit_depth - total_llm))
    return selected_indices


# ============================================================
# Qwen2.5-Omni Thinker 隐状态提取器
# ============================================================

class QwenOmniThinkerExtractor(nn.Module):
    """
    冻结的 Qwen2.5-Omni Thinker 语言模型，用作文本特征提取器。

    特点:
        - 只保留 Thinker 的语言模型 backbone
        - 丢弃 vision/audio_tower/talker/token2wav 等子模块节省显存
        - 前加领域特定 system prompt，输出时切掉 system prompt 部分
        - 输出每层的隐状态列表 (长度 = dit_depth)

    返回:
        extracted_states: List[Tensor], 长度 = dit_depth
            每个 Tensor 形状 [B, user_seq_len, hidden_dim]
        user_attention_mask: [B, user_seq_len]
        omni_last_emb (可选): 单层全局嵌入
    """

    def __init__(
        self,
        model_path: str = "Qwen/Qwen2.5-Omni-7B",
        dit_depth: int = 20,
        select_mode: str = "interval",
        device: str = "cuda",
        dtype: torch.dtype = torch.bfloat16,
        omni_last_layer_idx: Optional[int] = None,
        max_length: int = 256,
    ):
        super().__init__()
        self.device = device
        self.dtype = dtype
        self.max_length = max_length

        # 加载完整模型后，只保留语言模型 backbone
        from transformers import Qwen2_5OmniForConditionalGeneration

        full_model = Qwen2_5OmniForConditionalGeneration.from_pretrained(
            model_path,
            torch_dtype=dtype,
            device_map="cpu",
            attn_implementation="flash_attention_2",
        )
        self.text_backbone = full_model.thinker.model.eval()

        # 冻结所有参数
        for param in self.text_backbone.parameters():
            param.requires_grad = False

        # 丢弃不需要的子模块
        del full_model.talker
        del full_model.token2wav
        del full_model.thinker.visual
        del full_model.thinker.audio_tower
        del full_model
        gc.collect()

        self.text_backbone = self.text_backbone.to(device)
        torch.cuda.empty_cache()

        # 加载 processor，右侧 padding (system prompt 总在 index 0)
        from transformers import Qwen2_5OmniProcessor
        self.processor = Qwen2_5OmniProcessor.from_pretrained(model_path)
        self.processor.tokenizer.padding_side = "right"

        # 领域特定的 system prompt
        self.system_prompt_content = [{
            "type": "text",
            "text": (
                "You are an expert Audio Director and Sound Engineer. "
                "Your task is to mentally simulate and analyze the acoustic scene described in the text. "
                "Pay attention to the following three layers: "
                "1. Voice & Prosody: If there is speech, identify the speaker's gender, age, emotion, accent, and exact spoken content. "
                "2. Environmental Sounds: Identify background ambience, distinct sound effects, and their textures. "
                "3. Spatial Mix: Determine how the voice and background sounds overlap and interact in the scene. "
                "Extract deep semantic representations to guide the generation of high-fidelity speech, audio, or a mixture of both."
            )
        }]

        # 预计算 system prompt 的 token 数，前向时切掉这部分
        sys_str = self.processor.apply_chat_template(
            [{"role": "system", "content": self.system_prompt_content}],
            add_generation_prompt=False,
            tokenize=False,
        )
        sys_tokens = self.processor(
            sys_str, return_tensors="pt", padding=False, truncation=False, add_special_tokens=False
        )
        self.system_token_len = sys_tokens.input_ids.shape[1]

        # 采样层索引
        self.total_llm_layers = len(self.text_backbone.layers)
        self.layer_indices = get_layer_indices(self.total_llm_layers, dit_depth, select_mode)

        self.omni_last_layer_idx = omni_last_layer_idx

    @torch.no_grad()
    def forward(self, text_list: list) -> tuple:
        """
        提取每个 DiT 块对应的隐状态。

        Args:
            text_list: 文本提示列表 (batch)

        Returns:
            extracted_states: List[Tensor] 长度=dit_depth，每层 [B, L_user, D]
            user_attention_mask: [B, L_user]
            omni_last_emb (可选): 单层全局嵌入 [B, L_user, D]
        """
        # 构建对话: system + user
        batch_conversations = [
            [
                {"role": "system", "content": self.system_prompt_content},
                {"role": "user", "content": [{"type": "text", "text": txt}]},
            ]
            for txt in text_list
        ]

        text_prompts = self.processor.apply_chat_template(
            batch_conversations, add_generation_prompt=True, tokenize=False,
        )

        # Tokenize (右侧 padding: [System][User][Pad…])
        inputs = self.processor(
            text_prompts,
            return_tensors="pt",
            padding="max_length",
            truncation=True,
            max_length=self.max_length,
            add_special_tokens=False,
        ).to(self.device)

        # 前向传播，获取所有隐状态
        outputs = self.text_backbone(
            input_ids=inputs.input_ids,
            attention_mask=inputs.attention_mask,
            output_hidden_states=True,
            return_dict=True,
            use_cache=False,
        )
        all_states = outputs.hidden_states

        # 切掉 system prompt 部分，只保留用户提示的 token
        extracted_states = [
            all_states[idx].to(self.dtype)[:, self.system_token_len:, :]
            for idx in self.layer_indices
        ]
        user_attention_mask = inputs.attention_mask[:, self.system_token_len:]

        if self.omni_last_layer_idx is not None:
            omni_last_emb = all_states[self.omni_last_layer_idx].to(
                self.dtype
            )[:, self.system_token_len:, :]
            return extracted_states, user_attention_mask, omni_last_emb

        return extracted_states, user_attention_mask


# ============================================================
# Qwen3 Causal LM 隐状态提取器
# ============================================================

class Qwen3CausalLMHiddenExtractor(nn.Module):
    """
    Qwen3 Causal LM 隐状态提取器 (纯文本版本)。

    与 Omni 版本的区别:
        - 不使用 system prompt
        - 使用 chat template (如果 tokenizer 定义了)
        - 模型更小更快 (0.6B / 1.7B / 4B)

    预设模型:
        - qwen3-4b-instruct: hidden_size=2560, 36 layers
        - qwen3-1.7b: hidden_size=2048, 28 layers
        - qwen3-0.6b: hidden_size=1024, 28 layers
    """

    def __init__(
        self,
        model_path: str,
        dit_depth: int = 20,
        select_mode: str = "interval",
        device="cuda",
        dtype=torch.bfloat16,
        omni_last_layer_idx: Optional[int] = None,
        max_length: int = 256,
    ):
        super().__init__()
        self.device = device
        self.dtype = dtype
        self.max_length = max_length
        self.omni_last_layer_idx = omni_last_layer_idx

        from transformers import AutoModelForCausalLM, AutoTokenizer

        full_model = AutoModelForCausalLM.from_pretrained(
            model_path, torch_dtype=dtype, device_map="cpu",
            attn_implementation="sdpa",
        )
        self.text_backbone = full_model.model.eval()
        for p in self.text_backbone.parameters():
            p.requires_grad = False

        del full_model
        gc.collect()
        self.text_backbone = self.text_backbone.to(device)
        torch.cuda.empty_cache()

        self.tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)
        if self.tokenizer.pad_token is None:
            self.tokenizer.pad_token = self.tokenizer.eos_token
        self.tokenizer.padding_side = "right"

        self.total_llm_layers = len(self.text_backbone.layers)
        self.layer_indices = get_layer_indices(self.total_llm_layers, dit_depth, select_mode)

    @torch.no_grad()
    def forward(self, text_list: List[str]):
        """提取多层隐状态 (返回格式与 Omni 版本一致)"""
        use_chat = getattr(self.tokenizer, "chat_template", None) is not None
        if use_chat:
            prompts = []
            for txt in text_list:
                messages = [{"role": "user", "content": txt}]
                p = self.tokenizer.apply_chat_template(
                    messages, tokenize=False, add_generation_prompt=True,
                )
                prompts.append(p)
        else:
            prompts = list(text_list)

        inputs = self.tokenizer(
            prompts, return_tensors="pt", padding="max_length",
            truncation=True, max_length=self.max_length,
            add_special_tokens=False if use_chat else True,
        ).to(self.device)

        outputs = self.text_backbone(
            input_ids=inputs.input_ids,
            attention_mask=inputs.attention_mask,
            output_hidden_states=True,
            return_dict=True,
            use_cache=False,
        )
        all_states = outputs.hidden_states

        extracted_states = []
        for idx in self.layer_indices:
            feat = all_states[idx].to(self.dtype)
            extracted_states.append(feat)

        user_attention_mask = inputs.attention_mask

        if self.omni_last_layer_idx is not None:
            omni_last_emb = all_states[self.omni_last_layer_idx].to(self.dtype)
            return extracted_states, user_attention_mask, omni_last_emb

        return extracted_states, user_attention_mask


# ============================================================
# 深度融合投影 (在 DiT backbone 中)
# ============================================================
"""
深度融合投影是 UNISON 的核心机制，在 UnisonBackbone 中定义:

```python
# deep_fusion_projs: ModuleList，每个 DiT 块对应一个独立投影
self.deep_fusion_projs = nn.ModuleList([
    nn.Linear(omni_dim, hidden_size) for _ in range(self.total_blocks_depth)
])
```

每个 DiT 块 i 的前向流程:

1. 获取第 i 个 MLLM 隐状态: omni_emb_list[i]  [B, L_text, omni_dim]
2. 投影到 hidden_size: omni_curr = deep_fusion_projs[i](omni_emb_list[i])
3. 与 txt_base 拼接/打包: txt_packed = pack([txt_base, omni_curr])
4. 送入 MMDoubleStreamBlock / MMSingleStreamBlock 的文本分支
5. 通过联合注意力 (parallel_attention) 与音频潜在交互

层次化对齐:
    DiT Block 0  ←  LLM Layer  2  (浅层: 词汇、音韵)
    DiT Block 5  ←  LLM Layer  9  (中层: 句法结构)
    DiT Block 10 ←  LLM Layer 16  (中深层: 语义)
    DiT Block 15 ←  LLM Layer 23  (深层: 抽象语义)
    DiT Block 19 ←  LLM Layer 28  (最顶层: 整体语义)

这种设计让不同层级的 DiT 块接收不同抽象程度的文本信息，
提高了跨任务的文本遵循能力。
"""
