# Generated by Trae Work
"""
UNISON DiT 主干 — UnisonBackbone (MM-DiT with Deep LLM Fusion)

核心架构: MM-DiT (Multi-Modal Diffusion Transformer)
- Double Stream Blocks: 音频 + 文本 双流联合注意力
- Single Stream Blocks: 音频 + 文本 合并为单流自注意力

输入格式 (Channel-cat 设计):
    x: [B, 2*C+1, T]
        x[:, :C, :]    = 噪声目标潜在 z_t
        x[:, C:2C, :]  = 源/参考潜在 z_s (生成任务时为 0)
        x[:, 2C, :]    = 任务掩码 m (0=生成, 1=编辑, 2=零样本TTS参考区)

Deep LLM Fusion (核心创新):
    每个 DiT 块接收 MLLM 对应层的隐状态，通过独立线性投影后
    作为文本 token 参与联合注意力，实现层次化对齐。

参考文件:
- transformers/backbone.py
- transformers/modules/modulate_layers.py
- transformers/modules/embed_layers.py
- transformers/modules/attention.py
"""

from typing import List, Tuple, Optional, Union

import torch
import torch.nn as nn
import torch.nn.functional as F
from einops import rearrange


# ============================================================
# 基础工具：调制 & 门控
# ============================================================

def modulate(x: torch.Tensor, shift: torch.Tensor = None, scale: torch.Tensor = None) -> torch.Tensor:
    """AdaLN 调制: x * (1 + scale) + shift"""
    if scale is None and shift is None:
        return x
    elif shift is None:
        return x * (1 + scale.unsqueeze(1))
    elif scale is None:
        return x + shift.unsqueeze(1)
    else:
        return x * (1 + scale.unsqueeze(1)) + shift.unsqueeze(1)


def apply_gate(x: torch.Tensor, gate: torch.Tensor = None) -> torch.Tensor:
    """门控残差: x * gate"""
    if gate is None:
        return x
    return x * gate.unsqueeze(1)


class ModulateDiT(nn.Module):
    """
    DiT 调制层。
    输入全局条件 vec，输出 shift/scale/gate 参数。
    factor=6 时输出 6 个参数 (MSA×3 + MLP×3)。
    零初始化确保初始时调制为 0。
    """
    def __init__(self, hidden_size: int, factor: int, act_layer):
        super().__init__()
        self.act = act_layer()
        self.linear = nn.Linear(hidden_size, factor * hidden_size, bias=True)
        nn.init.zeros_(self.linear.weight)
        nn.init.zeros_(self.linear.bias)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.linear(self.act(x))


# ============================================================
# 时间步嵌入
# ============================================================

def timestep_embedding(t: torch.Tensor, dim: int, max_period: int = 10000) -> torch.Tensor:
    """正弦时间步嵌入"""
    half = dim // 2
    freqs = torch.exp(
        -math.log(max_period) * torch.arange(start=0, end=half, dtype=torch.float32) / half
    ).to(device=t.device)
    args = t[:, None].float() * freqs[None]
    embedding = torch.cat([torch.cos(args), torch.sin(args)], dim=-1)
    if dim % 2:
        embedding = torch.cat([embedding, torch.zeros_like(embedding[:, :1])], dim=-1)
    return embedding


class TimestepEmbedder(nn.Module):
    """将标量时间步嵌入为向量 (正弦编码 + 2层 MLP)"""
    def __init__(self, hidden_size: int, act_layer, frequency_embedding_size: int = 256):
        super().__init__()
        self.mlp = nn.Sequential(
            nn.Linear(frequency_embedding_size, hidden_size, bias=True),
            act_layer(),
            nn.Linear(hidden_size, hidden_size, bias=True),
        )
        nn.init.normal_(self.mlp[0].weight, std=0.02)
        nn.init.normal_(self.mlp[2].weight, std=0.02)

    def forward(self, t: torch.Tensor) -> torch.Tensor:
        t_freq = timestep_embedding(t, 256).type(self.mlp[0].weight.dtype)
        return self.mlp(t_freq)


# ============================================================
# RoPE (1D 音频)
# ============================================================

def get_audio_rotary_pos_embed(
    rope_dim_list: list,
    length: int,
    theta: int = 10000,
    freqs_scaling: float = 1.0,
    use_real: bool = True
) -> Tuple[torch.Tensor, torch.Tensor]:
    """1D 音频 RoPE 位置编码"""
    dim = rope_dim_list[0]
    pos = torch.arange(length, dtype=torch.float32)
    omega = torch.arange(dim // 2, dtype=torch.float32) / (dim // 2 - 1)
    omega = 1.0 / (theta ** omega)
    omega = omega * freqs_scaling
    freqs = torch.outer(pos, omega)
    cos = torch.cos(freqs)
    sin = torch.sin(freqs)
    return cos, sin


def apply_rotary_emb(
    xq: torch.Tensor, xk: torch.Tensor, freqs_cis: Tuple[torch.Tensor, torch.Tensor],
    head_first: bool = False
) -> Tuple[torch.Tensor, torch.Tensor]:
    """应用 RoPE 到 Q 和 K"""
    cos, sin = freqs_cis

    if head_first:
        # xq: [B, H, L, D]
        xq_out = xq.float()
        xk_out = xk.float()
        cos = cos.unsqueeze(0).unsqueeze(0)  # [1, 1, L, D]
        sin = sin.unsqueeze(0).unsqueeze(0)
    else:
        # xq: [B, L, H, D]
        xq_out = xq.float()
        xk_out = xk.float()
        cos = cos.unsqueeze(0).unsqueeze(1)  # [1, 1, L, D]
        sin = sin.unsqueeze(0).unsqueeze(1)

    xq_rot = xq_out * cos + _rotate_half(xq_out) * sin
    xk_rot = xk_out * cos + _rotate_half(xk_out) * sin
    return xq_rot.to(xq.dtype), xk_rot.to(xk.dtype)


def _rotate_half(x: torch.Tensor) -> torch.Tensor:
    x1 = x[..., : x.shape[-1] // 2]
    x2 = x[..., x.shape[-1] // 2:]
    return torch.cat((-x2, x1), dim=-1)


# ============================================================
# 双流 MMDiT 块 (Double Stream)
# ============================================================

class MMDoubleStreamBlock(nn.Module):
    """
    双流 DiT 块 (音频 + 文本 联合注意力)。

    结构:
        音频分支: img_norm1 → AdaLN → QKV → 联合注意力 → img_attn_proj → 门控残差
                         → img_norm2 → AdaLN → MLP → 门控残差
        文本分支: txt_norm1 → AdaLN → QKV → 联合注意力 → txt_attn_proj → 门控残差
                         → txt_norm2 → AdaLN → MLP → 门控残差

    关键: 两个分支的 Q/K/V 拼接后做一次自注意力 (parallel_attention)，
    实现跨模态的 token 级交互。
    """
    def __init__(
        self,
        hidden_size: int,
        heads_num: int,
        mlp_width_ratio: float = 4.0,
        mlp_act_type: str = "gelu_tanh",
        qk_norm: bool = True,
        qk_norm_type: str = "rms",
        qkv_bias: bool = False,
        has_text_ffn: bool = True,
    ):
        super().__init__()
        self.heads_num = heads_num
        self.has_text_ffn = has_text_ffn
        head_dim = hidden_size // heads_num
        mlp_hidden_dim = int(hidden_size * mlp_width_ratio)

        # --- 音频分支 ---
        self.img_mod = ModulateDiT(hidden_size, factor=6, act_layer=nn.SiLU)
        self.img_norm1 = nn.LayerNorm(hidden_size, elementwise_affine=False, eps=1e-6)
        self.img_attn_q = nn.Linear(hidden_size, hidden_size, bias=qkv_bias)
        self.img_attn_k = nn.Linear(hidden_size, hidden_size, bias=qkv_bias)
        self.img_attn_v = nn.Linear(hidden_size, hidden_size, bias=qkv_bias)
        self.img_attn_q_norm = nn.LayerNorm(head_dim, elementwise_affine=True, eps=1e-6) if qk_norm else nn.Identity()
        self.img_attn_k_norm = nn.LayerNorm(head_dim, elementwise_affine=True, eps=1e-6) if qk_norm else nn.Identity()
        self.img_attn_proj = nn.Linear(hidden_size, hidden_size, bias=qkv_bias)

        self.img_norm2 = nn.LayerNorm(hidden_size, elementwise_affine=False, eps=1e-6)
        self.img_mlp = nn.Sequential(
            nn.Linear(hidden_size, mlp_hidden_dim, bias=True),
            nn.GELU(),
            nn.Linear(mlp_hidden_dim, hidden_size, bias=True),
        )

        # --- 文本分支 ---
        txt_mod_factor = 6 if has_text_ffn else 2
        self.txt_mod = ModulateDiT(hidden_size, factor=txt_mod_factor, act_layer=nn.SiLU)
        self.txt_norm1 = nn.LayerNorm(hidden_size, elementwise_affine=False, eps=1e-6)
        self.txt_attn_q = nn.Linear(hidden_size, hidden_size, bias=qkv_bias)
        self.txt_attn_k = nn.Linear(hidden_size, hidden_size, bias=qkv_bias)
        self.txt_attn_v = nn.Linear(hidden_size, hidden_size, bias=qkv_bias)
        self.txt_attn_q_norm = nn.LayerNorm(head_dim, elementwise_affine=True, eps=1e-6) if qk_norm else nn.Identity()
        self.txt_attn_k_norm = nn.LayerNorm(head_dim, elementwise_affine=True, eps=1e-6) if qk_norm else nn.Identity()

        if has_text_ffn:
            self.txt_attn_proj = nn.Linear(hidden_size, hidden_size, bias=qkv_bias)
            self.txt_norm2 = nn.LayerNorm(hidden_size, elementwise_affine=False, eps=1e-6)
            self.txt_mlp = nn.Sequential(
                nn.Linear(hidden_size, mlp_hidden_dim, bias=True),
                nn.GELU(),
                nn.Linear(mlp_hidden_dim, hidden_size, bias=True),
            )

    def forward(
        self,
        img: torch.Tensor,
        txt: torch.Tensor,
        vec: torch.Tensor,
        freqs_cis: tuple = None,
        text_mask=None,
    ) -> Tuple[torch.Tensor, torch.Tensor]:
        """
        Args:
            img: [B, L_img, D] 音频潜在
            txt: [B, L_txt, D] 文本嵌入 (MLLM隐状态投影后)
            vec: [B, 1, D] 全局条件 (时间步 + 全局文本)
            freqs_cis: RoPE 位置编码
            text_mask: [B, L_txt] 文本掩码

        Returns:
            img, txt: 更新后的音频和文本
        """
        # AdaLN 调制参数
        (img_mod1_shift, img_mod1_scale, img_mod1_gate,
         img_mod2_shift, img_mod2_scale, img_mod2_gate) = self.img_mod(vec).chunk(6, dim=-1)

        if self.has_text_ffn:
            (txt_mod1_shift, txt_mod1_scale, txt_mod1_gate,
             txt_mod2_shift, txt_mod2_scale, txt_mod2_gate) = self.txt_mod(vec).chunk(6, dim=-1)
        else:
            txt_mod1_shift, txt_mod1_scale = self.txt_mod(vec).chunk(2, dim=-1)

        # --- 音频 QKV ---
        img_modulated = modulate(self.img_norm1(img), shift=img_mod1_shift, scale=img_mod1_scale)
        img_q = rearrange(self.img_attn_q(img_modulated), "B L (H D) -> B L H D", H=self.heads_num)
        img_k = rearrange(self.img_attn_k(img_modulated), "B L (H D) -> B L H D", H=self.heads_num)
        img_v = rearrange(self.img_attn_v(img_modulated), "B L (H D) -> B L H D", H=self.heads_num)
        img_q = self.img_attn_q_norm(img_q).to(img_v)
        img_k = self.img_attn_k_norm(img_k).to(img_v)

        if freqs_cis is not None:
            img_q, img_k = apply_rotary_emb(img_q, img_k, freqs_cis, head_first=False)

        # --- 文本 QKV ---
        txt_modulated = modulate(self.txt_norm1(txt), shift=txt_mod1_scale, scale=txt_mod1_scale)
        txt_q = rearrange(self.txt_attn_q(txt_modulated), "B L (H D) -> B L H D", H=self.heads_num)
        txt_k = rearrange(self.txt_attn_k(txt_modulated), "B L (H D) -> B L H D", H=self.heads_num)
        txt_v = rearrange(self.txt_attn_v(txt_modulated), "B L (H D) -> B L H D", H=self.heads_num)
        txt_q = self.txt_attn_q_norm(txt_q).to(txt_v)
        txt_k = self.txt_attn_k_norm(txt_k).to(txt_v)

        # --- 联合自注意力 (音频 Q 注意 音频+文本 KV) ---
        # 拼接 KV: 音频在前，文本在后
        joint_q = torch.cat([img_q, txt_q], dim=1)
        joint_k = torch.cat([img_k, txt_k], dim=1)
        joint_v = torch.cat([img_v, txt_v], dim=1)

        # SDPA 注意力
        joint_q_t = joint_q.transpose(1, 2)   # [B, H, L, D]
        joint_k_t = joint_k.transpose(1, 2)
        joint_v_t = joint_v.transpose(1, 2)

        # 构造 attention mask (处理文本 padding)
        attn_mask = None
        if text_mask is not None:
            # img 全有效，txt 按 mask
            img_len = img.shape[1]
            txt_len = txt.shape[1]
            full_mask = torch.ones(img_q.shape[0], img_len + txt_len, device=img.device)
            full_mask[:, img_len:] = text_mask.float()
            # 转换为 SDPA 用的 mask 格式
            attn_mask = full_mask.unsqueeze(1).unsqueeze(2)  # [B, 1, 1, L]
            attn_mask = attn_mask.to(dtype=joint_q_t.dtype)
            attn_mask = (1.0 - attn_mask) * torch.finfo(joint_q_t.dtype).min

        attn_out = F.scaled_dot_product_attention(joint_q_t, joint_k_t, joint_v_t, attn_mask=attn_mask)
        attn_out = attn_out.transpose(1, 2).contiguous()  # [B, L, H*D]
        attn_out = rearrange(attn_out, "B L H D -> B L (H D)")

        # 切回音频和文本
        img_len = img.shape[1]
        img_attn = attn_out[:, :img_len]
        txt_attn = attn_out[:, img_len:]

        # 门控残差
        img = img + apply_gate(self.img_attn_proj(img_attn), gate=img_mod1_gate)
        img = img + apply_gate(
            self.img_mlp(modulate(self.img_norm2(img), shift=img_mod2_shift, scale=img_mod2_scale)),
            gate=img_mod2_gate
        )

        if self.has_text_ffn:
            txt = txt + apply_gate(self.txt_attn_proj(txt_attn), gate=txt_mod1_gate)
            txt = txt + apply_gate(
                self.txt_mlp(modulate(self.txt_norm2(txt), shift=txt_mod2_shift, scale=txt_mod2_scale)),
                gate=txt_mod2_gate
            )

        return img, txt


# ============================================================
# 单流 MMDiT 块 (Single Stream)
# ============================================================

class MMSingleStreamBlock(nn.Module):
    """
    单流 DiT 块 (音频 + 文本 合并为单流)。

    结构:
        x = concat([img, txt], dim=1)
        → LayerNorm → AdaLN → QKV → 自注意力 + MLP → 门控残差
        → 切回 img, txt

    相比 Double Stream，参数更少，通常放在网络后期做细化。
    """
    def __init__(
        self,
        hidden_size: int,
        heads_num: int,
        mlp_width_ratio: float = 4.0,
        mlp_act_type: str = "gelu_tanh",
        qk_norm: bool = True,
        qk_norm_type: str = "rms",
    ):
        super().__init__()
        self.hidden_size = hidden_size
        self.heads_num = heads_num
        head_dim = hidden_size // heads_num
        mlp_hidden_dim = int(hidden_size * mlp_width_ratio)

        self.pre_norm = nn.LayerNorm(hidden_size, elementwise_affine=False, eps=1e-6)
        self.modulation = ModulateDiT(hidden_size, factor=3, act_layer=nn.SiLU)

        # 单组 QKV + MLP，共享权重
        self.linear1_q = nn.Linear(hidden_size, hidden_size)
        self.linear1_k = nn.Linear(hidden_size, hidden_size)
        self.linear1_v = nn.Linear(hidden_size, hidden_size)
        self.linear1_mlp = nn.Linear(hidden_size, mlp_hidden_dim)
        self.linear2 = nn.Linear(hidden_size + mlp_hidden_dim, hidden_size, bias=True)
        self.mlp_act = nn.GELU()

        self.q_norm = nn.LayerNorm(head_dim, elementwise_affine=True, eps=1e-6) if qk_norm else nn.Identity()
        self.k_norm = nn.LayerNorm(head_dim, elementwise_affine=True, eps=1e-6) if qk_norm else nn.Identity()

    def forward(
        self,
        x: torch.Tensor,
        vec: torch.Tensor,
        txt_len: int,
        freqs_cis: Tuple[torch.Tensor, torch.Tensor] = None,
        text_mask=None,
    ) -> torch.Tensor:
        """
        Args:
            x: [B, L_img + L_txt, D] 拼接的音频+文本
            vec: [B, 1, D] 全局条件
            txt_len: 文本 token 数 (用于切分 img/txt)
            freqs_cis: RoPE (只应用于音频部分)
            text_mask: 文本掩码

        Returns:
            x_out: [B, L_img + L_txt, D]
        """
        mod_shift, mod_scale, mod_gate = self.modulation(vec).chunk(3, dim=-1)
        x_mod = modulate(self.pre_norm(x), shift=mod_shift, scale=mod_scale)

        q = rearrange(self.linear1_q(x_mod), "B L (H D) -> B L H D", H=self.heads_num)
        k = rearrange(self.linear1_k(x_mod), "B L (H D) -> B L H D", H=self.heads_num)
        v = rearrange(self.linear1_v(x_mod), "B L (H D) -> B L H D", H=self.heads_num)
        mlp = self.linear1_mlp(x_mod)

        q = self.q_norm(q).to(v)
        k = self.k_norm(k).to(v)

        # RoPE 只应用于音频部分 (前 txt_len 之前的部分)
        img_len = x.shape[1] - txt_len
        if freqs_cis is not None:
            img_q = q[:, :img_len, :, :]
            img_k = k[:, :img_len, :, :]
            img_q, img_k = apply_rotary_emb(img_q, img_k, freqs_cis, head_first=False)
            q = torch.cat([img_q, q[:, img_len:, :, :]], dim=1)
            k = torch.cat([img_k, k[:, img_len:, :, :]], dim=1)

        # SDPA 注意力
        q_t = q.transpose(1, 2)
        k_t = k.transpose(1, 2)
        v_t = v.transpose(1, 2)

        attn_mask = None
        if text_mask is not None:
            full_mask = torch.ones(x.shape[0], x.shape[1], device=x.device)
            full_mask[:, img_len:] = text_mask.float()
            attn_mask = full_mask.unsqueeze(1).unsqueeze(2)
            attn_mask = attn_mask.to(dtype=q_t.dtype)
            attn_mask = (1.0 - attn_mask) * torch.finfo(q_t.dtype).min

        attn_out = F.scaled_dot_product_attention(q_t, k_t, v_t, attn_mask=attn_mask)
        attn_out = attn_out.transpose(1, 2).contiguous()
        attn_out = rearrange(attn_out, "B L H D -> B L (H D)")

        # 融合注意力输出和 MLP
        output = self.linear2(torch.cat([attn_out, self.mlp_act(mlp)], dim=-1))
        return x + apply_gate(output, gate=mod_gate)


# ============================================================
# 最终输出层
# ============================================================

class FinalLayer(nn.Module):
    """DiT 最终输出层: AdaLN → Linear"""
    def __init__(self, hidden_size: int, patch_size, out_channels: int, act_layer):
        super().__init__()
        self.norm_final = nn.LayerNorm(hidden_size, elementwise_affine=False, eps=1e-6)
        self.linear = nn.Linear(hidden_size, out_channels, bias=True)
        self.adaLN_modulation = nn.Sequential(
            act_layer(),
            nn.Linear(hidden_size, 2 * hidden_size, bias=True)
        )
        nn.init.zeros_(self.adaLN_modulation[-1].weight)
        nn.init.zeros_(self.adaLN_modulation[-1].bias)
        nn.init.zeros_(self.linear.weight)
        nn.init.zeros_(self.linear.bias)

    def forward(self, x: torch.Tensor, vec: torch.Tensor) -> torch.Tensor:
        shift, scale = self.adaLN_modulation(vec).chunk(2, dim=-1)
        x = modulate(self.norm_final(x), shift, scale)
        x = self.linear(x)
        return x


# ============================================================
# UnisonBackbone 主模型
# ============================================================

class UnisonBackbone(nn.Module):
    """
    UNISON DiT 主干 — 通道拼接 + 深度 LLM 融合。

    输入:
        x: [B, 2*C+1, T]
            - 前 C 维: 噪声目标潜在 z_t
            - 中 C 维: 源/参考潜在 z_s
            - 后 1 维: 任务掩码 m (0=生成, 1=编辑, 2=零样本TTS)
        t: [B] 时间步
        omni_emb_list: List[Tensor] MLLM 各层隐状态 (长度 = total_blocks_depth)
        omni_last_emb: Tensor MLLM 最后一层嵌入 (用作文本 base)
        omni_mask: [B, L] 文本掩码
        duration: [B] 时长嵌入 (可选)

    结构:
        UniversalPatchEmbed: 2C+1 → hidden_size (输入投影)
        TimestepEmbedder: t → vec (时间步嵌入)
        omni_last_proj: omni_last_emb → txt_base (文本 base 投影)
        deep_fusion_projs: N 个独立线性投影 (每层一个)
        double_blocks: mm_double_blocks_depth 个双流块
        single_blocks: mm_single_blocks_depth 个单流块
        FinalLayer: 输出

    深度融合流程 (每个 block i):
        1. omni_emb_list[i] → deep_fusion_projs[i] → omni_curr  [B, L, D]
        2. 与 txt_base 打包 → txt_packed
        3. 送入 block 的文本分支
        4. 联合注意力 → 跨模态交互
    """

    def __init__(
        self,
        in_channels: int = 48,
        out_channels: int = None,
        hidden_size: int = 1024,
        heads_num: int = 8,
        concat_condition: bool = True,
        mlp_act_type: str = "gelu_tanh",
        mlp_width_ratio: float = 4.0,
        mm_double_blocks_depth: int = 18,
        mm_single_blocks_depth: int = 0,
        qkv_bias: bool = True,
        qk_norm: bool = True,
        qk_norm_type: str = "rms",
        rope_dim_list: list = [64],
        rope_theta: int = 10000,
        omni_dim: int = 1280,
        use_duration_embedding: bool = False,
        use_omni_embedding: bool = True,
        use_omni_last_embedding: bool = False,
        projector_type: str = "linear",
        guidance_embed: bool = False,
        temporal_rope_scaling_factor: float = 1.0,
    ):
        super().__init__()

        self.hidden_size = hidden_size
        self.heads_num = heads_num
        self.concat_condition = concat_condition
        self.out_channels = out_channels or in_channels
        self.rope_dim_list = rope_dim_list
        self.rope_theta = rope_theta
        self.temporal_rope_scaling_factor = temporal_rope_scaling_factor
        self.mm_double_blocks_depth = mm_double_blocks_depth
        self.mm_single_blocks_depth = mm_single_blocks_depth
        self.total_blocks_depth = mm_double_blocks_depth + mm_single_blocks_depth
        self.guidance_embed = guidance_embed
        self.use_duration_embedding = use_duration_embedding
        self.use_omni_embedding = use_omni_embedding
        self.projector_type = projector_type
        self.use_omni_last_embedding = use_omni_last_embedding

        # --- 输入投影 (UniversalPatchEmbed 的音频简化版) ---
        # concat_condition=True 时输入通道 = 2*C + 1
        input_ch = in_channels * 2 + 1 if concat_condition else in_channels
        self.img_in = nn.Sequential(
            nn.Conv1d(input_ch, hidden_size, kernel_size=7, padding=3),
            nn.SiLU(),
            nn.Conv1d(hidden_size, hidden_size, kernel_size=3, padding=1),
        )
        # 初始化: 原始通道用 xavier，拼接通道用 zero
        nn.init.xavier_uniform_(self.img_in[0].weight[:, :in_channels, :].reshape(hidden_size, -1))
        with torch.no_grad():
            self.img_in[0].weight[:, in_channels:, :] = 0.0
        nn.init.zeros_(self.img_in[0].bias)

        # --- 时间步嵌入 ---
        self.time_in = TimestepEmbedder(hidden_size, nn.SiLU)
        self.guidance_in = TimestepEmbedder(hidden_size, nn.SiLU) if guidance_embed else None

        # --- 时长嵌入 ---
        self.duration_embedder = None
        if use_duration_embedding:
            self.duration_embedder = nn.Sequential(
                nn.Linear(1, hidden_size),
                nn.SiLU(),
                nn.Linear(hidden_size, hidden_size),
            )

        # --- 深度融合投影 (核心!) ---
        # 每个 DiT 块有一个独立的线性投影，将 MLLM 隐状态映射到 hidden_size
        if use_omni_embedding:
            if projector_type == "linear":
                self.deep_fusion_projs = nn.ModuleList([
                    nn.Linear(omni_dim, hidden_size) for _ in range(self.total_blocks_depth)
                ])
            elif projector_type == "mlp":
                self.deep_fusion_projs = nn.ModuleList([
                    nn.Sequential(
                        nn.Linear(omni_dim, hidden_size),
                        nn.SiLU(),
                        nn.Linear(hidden_size, hidden_size)
                    ) for _ in range(self.total_blocks_depth)
                ])
        else:
            self.deep_fusion_projs = None

        # --- 最后一层 MLLM 嵌入 (用作文本 base) ---
        if use_omni_last_embedding:
            self.omni_last_proj = nn.Linear(omni_dim, hidden_size)
        else:
            self.omni_last_proj = None

        need_text_ffn = use_omni_last_embedding or use_duration_embedding

        # --- 双流块 ---
        self.double_blocks = nn.ModuleList([
            MMDoubleStreamBlock(
                hidden_size=hidden_size,
                heads_num=heads_num,
                mlp_width_ratio=mlp_width_ratio,
                mlp_act_type=mlp_act_type,
                qk_norm=qk_norm,
                qk_norm_type=qk_norm_type,
                qkv_bias=qkv_bias,
                has_text_ffn=need_text_ffn,
            ) for _ in range(mm_double_blocks_depth)
        ])

        # --- 单流块 ---
        self.single_blocks = nn.ModuleList([
            MMSingleStreamBlock(
                hidden_size=hidden_size,
                heads_num=heads_num,
                mlp_width_ratio=mlp_width_ratio,
                mlp_act_type=mlp_act_type,
                qk_norm=qk_norm,
                qk_norm_type=qk_norm_type,
            ) for _ in range(mm_single_blocks_depth)
        ])

        # --- 输出层 ---
        self.final_layer = FinalLayer(hidden_size, (1, 1, 1), self.out_channels, nn.SiLU)

    def forward(
        self,
        x: torch.Tensor,
        t: torch.Tensor,
        duration: torch.Tensor = None,
        omni_emb_list: List[torch.Tensor] = None,
        omni_last_emb: torch.Tensor = None,
        omni_mask: torch.Tensor = None,
        guidance: torch.Tensor = None,
    ):
        """
        主前向传播。

        Args:
            x: [B, C_in, T] 输入 (噪声 + 参考 + 任务掩码，通道拼接)
            t: [B] 时间步
            omni_emb_list: List[Tensor[B, L_text, omni_dim]]  MLLM 各层隐状态
            omni_last_emb: Tensor[B, L_text, omni_dim]  MLLM 最后层嵌入
            omni_mask: [B, L_text] 文本掩码

        Returns:
            out: [B, C_out, T] 预测输出
        """
        # --- 1. 输入投影 & 时间步嵌入 ---
        # x: [B, C, T] → [B, T, C] (channel-last)
        img = x.transpose(1, 2)
        img = self.img_in(img.transpose(1, 2)).transpose(1, 2)  # Conv1d 需要 channel-first

        vec = self.time_in(t).unsqueeze(1)  # [B, 1, D]
        if self.guidance_embed and guidance is not None:
            vec = vec + self.guidance_in(guidance).unsqueeze(1)

        # --- 2. RoPE ---
        freqs_cos, freqs_sin = get_audio_rotary_pos_embed(
            rope_dim_list=self.rope_dim_list,
            length=img.shape[1],
            theta=self.rope_theta,
            freqs_scaling=self.temporal_rope_scaling_factor,
            use_real=True,
        )
        freqs_cis = (freqs_cos.to(img.device), freqs_sin.to(img.device))

        # --- 3. 构建文本 base ---
        txt_base = None
        txt_mask = None

        if self.use_omni_last_embedding:
            txt_base = self.omni_last_proj(omni_last_emb)
            txt_mask = omni_mask

        if self.duration_embedder is not None and duration is not None:
            dur_emb = self.duration_embedder(duration.unsqueeze(-1))
            dur_mask = torch.ones(omni_mask.shape[0], 1, device=omni_mask.device, dtype=omni_mask.dtype)
            if txt_base is not None:
                txt_base = torch.cat([dur_emb, txt_base], dim=1)
                txt_mask = torch.cat([dur_mask, txt_mask], dim=1)
            else:
                txt_base = dur_emb
                txt_mask = dur_mask

        has_base = txt_base is not None
        txt_base_len = txt_base.shape[1] if has_base else 0

        # --- 4. 双流块循环 + 深度融合 ---
        for i, block in enumerate(self.double_blocks):
            # 深度融合: 第 i 个 MLLM 隐状态 → 投影 → 与 txt_base 打包
            if self.use_omni_embedding:
                omni_curr = self.deep_fusion_projs[i](omni_emb_list[i])
                if has_base:
                    txt_packed = torch.cat([txt_base, omni_curr], dim=1)
                    txt_mask_packed = torch.cat([txt_mask, omni_mask], dim=1)
                else:
                    txt_packed = omni_curr
                    txt_mask_packed = omni_mask
            else:
                txt_packed = txt_base
                txt_mask_packed = txt_mask

            # 双流块前向
            img, txt_out_packed = block(
                img=img, txt=txt_packed, vec=vec,
                freqs_cis=freqs_cis, text_mask=txt_mask_packed,
            )

            # 恢复 txt_base (只保留 base 部分，深层特征在每层重新注入)
            if self.use_omni_embedding and has_base:
                txt_base = txt_out_packed[:, :txt_base_len, :]
            elif not self.use_omni_embedding:
                txt_base = txt_out_packed

        # --- 5. 单流块循环 ---
        img_len = img.shape[1]
        block_idx_offset = self.mm_double_blocks_depth

        for i, block in enumerate(self.single_blocks):
            if self.use_omni_embedding:
                omni_curr = self.deep_fusion_projs[block_idx_offset + i](
                    omni_emb_list[block_idx_offset + i]
                )
                if has_base:
                    txt_packed = torch.cat([txt_base, omni_curr], dim=1)
                    txt_mask_packed = torch.cat([txt_mask, omni_mask], dim=1)
                else:
                    txt_packed = omni_curr
                    txt_mask_packed = omni_mask
            else:
                txt_packed = txt_base
                txt_mask_packed = txt_mask

            x_in = torch.cat([img, txt_packed], dim=1)
            txt_len_packed = txt_packed.shape[1]

            x_out = block(
                x=x_in, vec=vec, txt_len=txt_len_packed,
                freqs_cis=freqs_cis, text_mask=txt_mask_packed,
            )

            img = x_out[:, :img_len, :]
            txt_out_packed = x_out[:, img_len:, :]

            if self.use_omni_embedding and has_base:
                txt_base = txt_out_packed[:, :txt_base_len, :]
            elif not self.use_omni_embedding:
                txt_base = txt_out_packed

        # --- 6. 输出层 ---
        img_out = self.final_layer(img, vec)
        out = img_out.transpose(1, 2).contiguous()  # [B, T, C] → [B, C, T]

        return out


# ============================================================
# 整体流程与数学总结
# ============================================================
"""
## UNISON 整体架构

              ┌─────────────────────────────────────┐
              │          文本指令 prompt            │
              └──────────────┬──────────────────────┘
                             │
                             ▼
              ┌─────────────────────────────────────┐
              │  MLLM (Qwen2.5-Omni / Qwen3)        │
              │  (冻结，只提取隐状态)               │
              └───────┬───────┬───────────┬─────────┘
                      │       │           │
                layer 2  layer 10  ...  layer 28
                      │       │           │
                      ▼       ▼           ▼
              ┌───────┐  ┌────┐       ┌──────┐
              │proj[0]│  │proj│  ...  │proj[N]│   ← deep_fusion_projs
              └───┬───┘  └─┬──┘       └──┬───┘
                  │        │             │
                  ▼        ▼             ▼
         ┌──────────────────────────────────────┐
         │         DiT (MM-DiT)                 │
         │  Block 0  ←  LLM layer 2  (词汇层)   │
         │  Block 5  ←  LLM layer 9  (句法层)   │
         │  Block 10 ←  LLM layer 16 (语义层)   │
         │  Block 19 ←  LLM layer 28 (顶层)     │
         └───────────────┬──────────────────────┘
                         │
                         ▼
              ┌─────────────────────────────────┐
              │  预测输出 (噪声/速度/数据)       │
              └─────────────────────────────────┘

## 输入张量格式 (Channel-cat)

    x = [z_t | z_s | m]  ∈ R^{B × 2C+1 × T}
        z_t: 噪声目标潜在 (C 维)
        z_s: 源/参考潜在 (C 维)，生成任务时为 0
        m:   任务掩码 (1 维)，按帧广播
             m=0: 生成任务 (T2A, TTS, T2AS)
             m=1: 编辑任务
             m=2: 零样本 TTS 参考区

## 深度融合 (Deep Fusion) 细节

每个 DiT 块 i:
1. 取 omni_emb_list[i] = MLLM 第 layer_indices[i] 层隐状态
2. 投影: omni_curr = deep_fusion_projs[i](omni_emb_list[i])
3. 与 txt_base 拼接 → txt_packed
4. 送入 block 的文本分支，与音频做联合注意力
5. 注意力后，只保留 txt_base 部分，丢弃 omni_curr 部分
   (因为下一层会注入新的 MLLM 隐状态)

这种设计的优势:
- 层次化对齐: 不同层级 DiT 块接收不同抽象程度的文本信息
- 参数高效: 每个投影只有 omni_dim × hidden_size 参数
- 计算高效: MLLM 只跑一次，各层隐状态被复用
"""

import math
