# Generated by Trae Work
"""
UNISON VAE — 1D 梅尔频谱变分自编码器

基于 ResNet 风格的 1D 卷积 VAE，在梅尔频谱域操作。
输入为 80 维 (16kHz) 或 128 维 (44kHz) 梅尔谱，输出 20/40 维潜在表示。

特点:
- 1D 卷积架构 (Encoder1D / Decoder1D)
- 中间层自注意力 (AttnBlock1D)
- 残差块 + 下采样/上采样
- 学习式增益 (learnable_gain) 控制输出幅度
- 激活裁剪 (clip_act=256) 稳定训练
- 数据归一化 (precomputed mean/std)

参考文件:
- mmaudio/ext/autoencoder/vae.py
- mmaudio/ext/autoencoder/vae_modules.py
- mmaudio/ext/autoencoder/autoencoder.py
- mmaudio/ext/autoencoder/distributions.py
"""

from typing import Optional
import torch
import torch.nn as nn
import torch.nn.functional as F


# ============================================================
# 分布：对角高斯后验
# ============================================================

class DiagonalGaussianDistribution(nn.Module):
    """
    对角高斯分布，用于 VAE 瓶颈。
    输入: moments [B, 2*C, T]，前 C 维是 mean，后 C 维是 logvar
    """
    def __init__(self, parameters: torch.Tensor, deterministic: bool = False):
        super().__init__()
        self.parameters = parameters
        self.mean, self.logvar = torch.chunk(parameters, 2, dim=1)
        self.logvar = torch.clamp(self.logvar, -30.0, 20.0)
        self.deterministic = deterministic
        self.std = torch.exp(0.5 * self.logvar)
        self.var = torch.exp(self.logvar)
        if self.deterministic:
            self.var = self.std = torch.zeros_like(
                self.mean, device=self.parameters.device, dtype=self.parameters.dtype
            )

    def sample(self, rng: Optional[torch.Generator] = None) -> torch.Tensor:
        """重参数化采样: z = mean + std * ε"""
        sample = torch.randn(self.mean.shape, generator=rng,
                             device=self.parameters.device, dtype=self.parameters.dtype)
        x = self.mean + self.std * sample
        return x

    def kl(self, other: Optional["DiagonalGaussianDistribution"] = None) -> torch.Tensor:
        """KL 散度: D_KL(N(μ,σ²) || N(0,1)) 或 D_KL(N(μ1,σ1²) || N(μ2,σ2²))"""
        if self.deterministic:
            return torch.Tensor([0.0])
        else:
            if other is None:
                return 0.5 * torch.sum(
                    torch.pow(self.mean, 2) + self.var - 1.0 - self.logvar,
                    dim=[1, 2]
                )
            else:
                return 0.5 * torch.sum(
                    torch.pow(self.mean - other.mean, 2) / other.var
                    + self.var / other.var - 1.0 - self.logvar + other.logvar,
                    dim=[1, 2]
                )

    def nll(self, sample: torch.Tensor, dims: list[int] = [1, 2, 3]) -> torch.Tensor:
        """负对数似然"""
        if self.deterministic:
            return torch.Tensor([0.0])
        logtwopi = torch.log(2.0 * torch.pi)
        return 0.5 * torch.sum(
            logtwopi + self.logvar + torch.pow(sample - self.mean, 2) / self.var,
            dim=dims
        )

    def mode(self) -> torch.Tensor:
        """分布模式 = mean"""
        return self.mean


# ============================================================
# 非线性激活
# ============================================================

def nonlinearity(x: torch.Tensor) -> torch.Tensor:
    """Swish / SiLU 激活"""
    return x * torch.sigmoid(x)


def Normalize(in_channels: int, num_groups: int = 32) -> nn.GroupNorm:
    """GroupNorm (默认 32 组)"""
    return nn.GroupNorm(
        num_groups=num_groups, num_channels=in_channels, eps=1e-6, affine=True
    )


# ============================================================
# 1D 残差块
# ============================================================

class ResnetBlock1D(nn.Module):
    """
    1D 残差块 (ResNet 风格)。
    两个 3x1 卷积 + GroupNorm + 非线性激活，可选短接投影。
    """
    def __init__(
        self,
        *,
        in_dim: int,
        out_dim: Optional[int] = None,
        conv_shortcut: bool = False,
        dropout: float = 0.0,
        temb_channels: int = 512,
        kernel_size: int = 3,
        use_norm: bool = True
    ):
        super().__init__()
        self.in_dim = in_dim
        out_dim = in_dim if out_dim is None else out_dim
        self.out_dim = out_dim
        self.use_norm = use_norm

        if use_norm:
            self.norm1 = Normalize(in_dim)
        self.conv1 = nn.Conv1d(in_dim, out_dim, kernel_size=kernel_size,
                               stride=1, padding=kernel_size // 2)
        if temb_channels > 0:
            self.temb_proj = nn.Linear(temb_channels, out_dim)
        if use_norm:
            self.norm2 = Normalize(out_dim)
        self.dropout = nn.Dropout(dropout)
        self.conv2 = nn.Conv1d(out_dim, out_dim, kernel_size=kernel_size,
                               stride=1, padding=kernel_size // 2)
        if in_dim != out_dim:
            if conv_shortcut:
                self.shortcut = nn.Conv1d(in_dim, out_dim, kernel_size=1)
            else:
                self.shortcut = nn.Conv1d(in_dim, out_dim, kernel_size=1)  # NinN
        else:
            self.shortcut = None

    def forward(self, x: torch.Tensor, temb: Optional[torch.Tensor] = None) -> torch.Tensor:
        h = x
        if self.use_norm:
            h = self.norm1(h)
        h = nonlinearity(h)
        h = self.conv1(h)

        if temb is not None:
            h = h + self.temb_proj(nonlinearity(temb))[:, :, None]

        if self.use_norm:
            h = self.norm2(h)
        h = nonlinearity(h)
        h = self.dropout(h)
        h = self.conv2(h)

        if self.shortcut is not None:
            x = self.shortcut(x)

        return x + h


# ============================================================
# 1D 自注意力块
# ============================================================

class AttnBlock1D(nn.Module):
    """
    1D 自注意力块 (全注意力，非局部)。
    类似于 Stable Diffusion 中的注意力块，但在 1D 上操作。
    """
    def __init__(self, in_channels: int):
        super().__init__()
        self.in_channels = in_channels

        self.norm = Normalize(in_channels)
        self.q = nn.Conv1d(in_channels, in_channels, kernel_size=1)
        self.k = nn.Conv1d(in_channels, in_channels, kernel_size=1)
        self.v = nn.Conv1d(in_channels, in_channels, kernel_size=1)
        self.proj_out = nn.Conv1d(in_channels, in_channels, kernel_size=1)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        h_ = self.norm(x)
        q = self.q(h_)
        k = self.k(h_)
        v = self.v(h_)

        # 计算注意力
        B, C, L = q.shape
        q = q.permute(0, 2, 1)            # [B, L, C]
        w_ = torch.bmm(q, k)              # [B, L, L]
        w_ = w_ * (int(C) ** (-0.5))
        w_ = F.softmax(w_, dim=2)

        # 乘 value
        w_ = w_.permute(0, 2, 1)
        h_ = torch.bmm(v, w_)             # [B, C, L]
        h_ = self.proj_out(h_)

        return x + h_


# ============================================================
# 下采样 / 上采样
# ============================================================

class Downsample1D(nn.Module):
    """下采样 (2x stride)，可选带卷积"""
    def __init__(self, in_channels: int, resample_with_conv: bool = True):
        super().__init__()
        self.in_channels = in_channels
        if resample_with_conv:
            self.conv = nn.Conv1d(in_channels, in_channels, kernel_size=3, stride=2, padding=1)
        else:
            self.conv = None

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        if self.conv is not None:
            return self.conv(x)
        else:
            return F.avg_pool1d(x, kernel_size=2, stride=2)


class Upsample1D(nn.Module):
    """上采样 (2x)，可选带卷积"""
    def __init__(self, in_channels: int, resample_with_conv: bool = True):
        super().__init__()
        self.in_channels = in_channels
        if resample_with_conv:
            self.conv = nn.Conv1d(in_channels, in_channels, kernel_size=3, stride=1, padding=1)
        else:
            self.conv = None

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        x = F.interpolate(x, scale_factor=2.0, mode="nearest")
        if self.conv is not None:
            x = self.conv(x)
        return x


# ============================================================
# VAE 主模型
# ============================================================

# 预计算的梅尔谱均值/标准差 (用于归一化)
DATA_MEAN_80D = [
    -1.6058, -1.3676, -1.2520, -1.2453, -1.2078, -1.2224, -1.2419, -1.2439, -1.2922, -1.2927,
    -1.3170, -1.3543, -1.3401, -1.3836, -1.3907, -1.3912, -1.4313, -1.4152, -1.4527, -1.4728,
    -1.4568, -1.5101, -1.5051, -1.5172, -1.5623, -1.5373, -1.5746, -1.5687, -1.6032, -1.6131,
    -1.6081, -1.6331, -1.6489, -1.6489, -1.6700, -1.6738, -1.6953, -1.6969, -1.7048, -1.7280,
    -1.7361, -1.7495, -1.7658, -1.7814, -1.7889, -1.8064, -1.8221, -1.8377, -1.8417, -1.8643,
    -1.8857, -1.8929, -1.9173, -1.9379, -1.9531, -1.9673, -1.9824, -2.0042, -2.0215, -2.0436,
    -2.0766, -2.1064, -2.1418, -2.1855, -2.2319, -2.2767, -2.3161, -2.3572, -2.3954, -2.4282,
    -2.4659, -2.5072, -2.5552, -2.6074, -2.6584, -2.7107, -2.7634, -2.8266, -2.8981, -2.9673
]

DATA_STD_80D = [
    1.0291, 1.0411, 1.0043, 0.9820, 0.9677, 0.9543, 0.9450, 0.9392, 0.9343, 0.9297, 0.9276, 0.9263,
    0.9242, 0.9254, 0.9232, 0.9281, 0.9263, 0.9315, 0.9274, 0.9247, 0.9277, 0.9199, 0.9188, 0.9194,
    0.9160, 0.9161, 0.9146, 0.9161, 0.9100, 0.9095, 0.9145, 0.9076, 0.9066, 0.9095, 0.9032, 0.9043,
    0.9038, 0.9011, 0.9019, 0.9010, 0.8984, 0.8983, 0.8986, 0.8961, 0.8962, 0.8978, 0.8962, 0.8973,
    0.8993, 0.8976, 0.8995, 0.9016, 0.8982, 0.8972, 0.8974, 0.8949, 0.8940, 0.8947, 0.8936, 0.8939,
    0.8951, 0.8956, 0.9017, 0.9167, 0.9436, 0.9690, 1.0003, 1.0225, 1.0381, 1.0491, 1.0545, 1.0604,
    1.0761, 1.0929, 1.1089, 1.1196, 1.1176, 1.1156, 1.1117, 1.1070
]


class VAE(nn.Module):
    """
    1D 梅尔频谱 VAE。

    架构:
        输入梅尔谱 [B, data_dim, T_mel]
            ↓ Encoder (多层残差块 + 下采样 + 中间注意力)
        moments [B, 2*embed_dim, T_lat]
            ↓ DiagonalGaussianDistribution (重参数化)
        z [B, embed_dim, T_lat]
            ↓ Decoder (多层残差块 + 上采样 + 中间注意力)
        重建梅尔谱 [B, data_dim, T_mel]

    16k 配置: data_dim=80, embed_dim=20, hidden_dim=384
    44k 配置: data_dim=128, embed_dim=40, hidden_dim=512
    """
    def __init__(
        self,
        *,
        data_dim: int,
        embed_dim: int,
        hidden_dim: int,
    ):
        super().__init__()

        # 数据归一化参数 (buffer，不参与训练)
        if data_dim == 80:
            self.data_mean = nn.Buffer(torch.tensor(DATA_MEAN_80D, dtype=torch.float32))
            self.data_std = nn.Buffer(torch.tensor(DATA_STD_80D, dtype=torch.float32))
        elif data_dim == 128:
            # 128 维也有预计算的 mean/std (此处省略完整列表)
            self.data_mean = nn.Buffer(torch.zeros(data_dim, dtype=torch.float32))
            self.data_std = nn.Buffer(torch.ones(data_dim, dtype=torch.float32))

        self.data_mean = self.data_mean.view(1, -1, 1)
        self.data_std = self.data_std.view(1, -1, 1)

        self.encoder = Encoder1D(
            dim=hidden_dim,
            ch_mult=(1, 2, 4),
            num_res_blocks=2,
            attn_layers=[3],
            down_layers=[0],
            in_dim=data_dim,
            embed_dim=embed_dim,
        )
        self.decoder = Decoder1D(
            dim=hidden_dim,
            ch_mult=(1, 2, 4),
            num_res_blocks=2,
            attn_layers=[3],
            down_layers=[0],
            in_dim=data_dim,
            out_dim=data_dim,
            embed_dim=embed_dim,
        )

        self.embed_dim = embed_dim

    def encode(self, x: torch.Tensor, normalize: bool = True) -> DiagonalGaussianDistribution:
        """编码: 梅尔谱 → 高斯后验"""
        if normalize:
            x = self.normalize(x)
        moments = self.encoder(x)
        posterior = DiagonalGaussianDistribution(moments)
        return posterior

    def decode(self, z: torch.Tensor, unnormalize: bool = True) -> torch.Tensor:
        """解码: 潜在表示 → 重建梅尔谱"""
        dec = self.decoder(z)
        if unnormalize:
            dec = self.unnormalize(dec)
        return dec

    def normalize(self, x: torch.Tensor) -> torch.Tensor:
        return (x - self.data_mean) / self.data_std

    def unnormalize(self, x: torch.Tensor) -> torch.Tensor:
        return x * self.data_std + self.data_mean

    def forward(
        self,
        x: torch.Tensor,
        sample_posterior: bool = True,
        rng: Optional[torch.Generator] = None,
        normalize: bool = True,
        unnormalize: bool = True,
    ) -> tuple[torch.Tensor, DiagonalGaussianDistribution]:
        posterior = self.encode(x, normalize=normalize)
        if sample_posterior:
            z = posterior.sample(rng)
        else:
            z = posterior.mode()
        dec = self.decode(z, unnormalize=unnormalize)
        return dec, posterior

    @property
    def device(self) -> torch.device:
        return next(self.parameters()).device

    def get_last_layer(self):
        return self.decoder.conv_out.weight

    def remove_weight_norm(self):
        """移除所有 MPConv1D 的权重归一化"""
        for m in self.modules():
            if hasattr(m, 'remove_weight_norm') and isinstance(m, nn.Conv1d):
                try:
                    nn.utils.remove_weight_norm(m)
                except:
                    pass
        return self


# ============================================================
# 编码器
# ============================================================

class Encoder1D(nn.Module):
    """
    1D VAE 编码器。

    结构:
        conv_in → [Level 0: ResBlock×2 → Attn → Downsample]
                 → [Level 1: ResBlock×2]
                 → [Level 2: ResBlock×2 → Attn]
                 → mid: ResBlock → Attn → ResBlock
                 → conv_out (2*embed_dim)
    """
    def __init__(self,
                 *,
                 dim: int,
                 ch_mult: tuple[int] = (1, 2, 4, 8),
                 num_res_blocks: int,
                 attn_layers: list[int] = [],
                 down_layers: list[int] = [],
                 resamp_with_conv: bool = True,
                 in_dim: int,
                 embed_dim: int,
                 double_z: bool = True,
                 kernel_size: int = 3,
                 clip_act: float = 256.0):
        super().__init__()
        self.dim = dim
        self.num_layers = len(ch_mult)
        self.num_res_blocks = num_res_blocks
        self.in_channels = in_dim
        self.clip_act = clip_act
        self.down_layers = down_layers
        self.attn_layers = attn_layers
        self.conv_in = nn.Conv1d(in_dim, self.dim, kernel_size=kernel_size, padding=kernel_size // 2)

        in_ch_mult = (1, ) + tuple(ch_mult)
        self.in_ch_mult = in_ch_mult

        # 下采样层级
        self.down = nn.ModuleList()
        for i_level in range(self.num_layers):
            block = nn.ModuleList()
            attn = nn.ModuleList()
            block_in = dim * in_ch_mult[i_level]
            block_out = dim * ch_mult[i_level]
            for i_block in range(self.num_res_blocks):
                block.append(
                    ResnetBlock1D(in_dim=block_in,
                                  out_dim=block_out,
                                  kernel_size=kernel_size,
                                  use_norm=True))
                block_in = block_out
                if i_level in attn_layers:
                    attn.append(AttnBlock1D(block_in))
            down = nn.Module()
            down.block = block
            down.attn = attn
            if i_level in down_layers:
                down.downsample = Downsample1D(block_in, resamp_with_conv)
            self.down.append(down)

        # 中间层
        self.mid = nn.Module()
        self.mid.block_1 = ResnetBlock1D(in_dim=block_in,
                                         out_dim=block_in,
                                         kernel_size=kernel_size,
                                         use_norm=True)
        self.mid.attn_1 = AttnBlock1D(block_in)
        self.mid.block_2 = ResnetBlock1D(in_dim=block_in,
                                         out_dim=block_in,
                                         kernel_size=kernel_size,
                                         use_norm=True)

        # 输出: 2*embed_dim (mean + logvar)
        self.conv_out = nn.Conv1d(block_in,
                                  2 * embed_dim if double_z else embed_dim,
                                  kernel_size=kernel_size,
                                  padding=kernel_size // 2)

        self.learnable_gain = nn.Parameter(torch.zeros([]))

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        # 下采样
        hs = [self.conv_in(x)]
        for i_level in range(self.num_layers):
            for i_block in range(self.num_res_blocks):
                h = self.down[i_level].block[i_block](hs[-1])
                if len(self.down[i_level].attn) > 0:
                    h = self.down[i_level].attn[i_block](h)
                h = h.clamp(-self.clip_act, self.clip_act)
                hs.append(h)
            if i_level in self.down_layers:
                hs.append(self.down[i_level].downsample(hs[-1]))

        # 中间
        h = hs[-1]
        h = self.mid.block_1(h)
        h = self.mid.attn_1(h)
        h = self.mid.block_2(h)
        h = h.clamp(-self.clip_act, self.clip_act)

        # 输出
        h = nonlinearity(h)
        h = self.conv_out(h) * (self.learnable_gain + 1)  # 学习式增益
        return h


# ============================================================
# 解码器
# ============================================================

class Decoder1D(nn.Module):
    """
    1D VAE 解码器，与编码器对称。

    结构:
        conv_in → mid: ResBlock → Attn → ResBlock
                 → [Level 2: ResBlock×3 → Attn]
                 → [Level 1: ResBlock×3]
                 → [Level 0: ResBlock×3 → Attn → Upsample]
                 → conv_out
    """
    def __init__(self,
                 *,
                 dim: int,
                 out_dim: int,
                 ch_mult: tuple[int] = (1, 2, 4, 8),
                 num_res_blocks: int,
                 attn_layers: list[int] = [],
                 down_layers: list[int] = [],
                 kernel_size: int = 3,
                 resamp_with_conv: bool = True,
                 in_dim: int,
                 embed_dim: int,
                 clip_act: float = 256.0):
        super().__init__()
        self.ch = dim
        self.num_layers = len(ch_mult)
        self.num_res_blocks = num_res_blocks
        self.in_channels = in_dim
        self.clip_act = clip_act
        self.down_layers = [i + 1 for i in down_layers]  # 每个下采样层增加一级

        block_in = dim * ch_mult[self.num_layers - 1]

        self.conv_in = nn.Conv1d(embed_dim, block_in, kernel_size=kernel_size, padding=kernel_size // 2)

        # 中间层
        self.mid = nn.Module()
        self.mid.block_1 = ResnetBlock1D(in_dim=block_in, out_dim=block_in, use_norm=True)
        self.mid.attn_1 = AttnBlock1D(block_in)
        self.mid.block_2 = ResnetBlock1D(in_dim=block_in, out_dim=block_in, use_norm=True)

        # 上采样层级
        self.up = nn.ModuleList()
        for i_level in reversed(range(self.num_layers)):
            block = nn.ModuleList()
            attn = nn.ModuleList()
            block_out = dim * ch_mult[i_level]
            for i_block in range(num_res_blocks + 1):
                block.append(ResnetBlock1D(in_dim=block_in, out_dim=block_out, use_norm=True))
                block_in = block_out
                if i_level in attn_layers:
                    attn.append(AttnBlock1D(block_in))
            up = nn.Module()
            up.block = block
            up.attn = attn
            if i_level in self.down_layers:
                up.upsample = Upsample1D(block_in, resamp_with_conv)
            self.up.insert(0, up)

        self.conv_out = nn.Conv1d(block_in, out_dim, kernel_size=kernel_size, padding=kernel_size // 2)
        self.learnable_gain = nn.Parameter(torch.zeros([]))

    def forward(self, z: torch.Tensor) -> torch.Tensor:
        h = self.conv_in(z)

        # 中间
        h = self.mid.block_1(h)
        h = self.mid.attn_1(h)
        h = self.mid.block_2(h)
        h = h.clamp(-self.clip_act, self.clip_act)

        # 上采样
        for i_level in reversed(range(self.num_layers)):
            for i_block in range(self.num_res_blocks + 1):
                h = self.up[i_level].block[i_block](h)
                if len(self.up[i_level].attn) > 0:
                    h = self.up[i_level].attn[i_block](h)
                h = h.clamp(-self.clip_act, self.clip_act)
            if i_level in self.down_layers:
                h = self.up[i_level].upsample(h)

        h = nonlinearity(h)
        h = self.conv_out(h) * (self.learnable_gain + 1)
        return h


# ============================================================
# AutoEncoderModule (VAE + Vocoder 包装)
# ============================================================

class AutoEncoderModule(nn.Module):
    """
    VAE + Vocoder 完整包装类，用于扩散模型流水线。

    流程:
        波形 → mel_converter → 梅尔谱 → VAE.encode → z (潜在)
        z → VAE.decode → 梅尔谱 → vocoder → 波形

    Vocoder 选项:
        - 16k: BigVGAN
        - 44k: BigVGANv2
    """
    def __init__(
        self,
        *,
        vae_ckpt_path: str,
        vocoder_ckpt_path: Optional[str] = None,
        mode: str = '16k',
        need_vae_encoder: bool = True
    ):
        super().__init__()
        if mode == '16k':
            self.vae = VAE(data_dim=80, embed_dim=20, hidden_dim=384).eval()
        elif mode == '44k':
            self.vae = VAE(data_dim=128, embed_dim=40, hidden_dim=512).eval()
        else:
            raise ValueError(f'Unknown mode: {mode}')

        vae_state_dict = torch.load(vae_ckpt_path, weights_only=True, map_location='cpu')
        self.vae.load_state_dict(vae_state_dict)

        for param in self.parameters():
            param.requires_grad = False

        if not need_vae_encoder:
            del self.vae.encoder

    @torch.inference_mode()
    def encode(self, x: torch.Tensor) -> DiagonalGaussianDistribution:
        """梅尔谱 → 潜在高斯分布"""
        return self.vae.encode(x)

    @torch.inference_mode()
    def decode(self, z: torch.Tensor) -> torch.Tensor:
        """潜在表示 → 重建梅尔谱"""
        return self.vae.decode(z)


# ============================================================
# 预设配置
# ============================================================

def VAE_16k(**kwargs) -> VAE:
    """16kHz 配置: 80维梅尔谱, 20维潜在, 384隐藏"""
    return VAE(data_dim=80, embed_dim=20, hidden_dim=384, **kwargs)


def VAE_44k(**kwargs) -> VAE:
    """44kHz 配置: 128维梅尔谱, 40维潜在, 512隐藏"""
    return VAE(data_dim=128, embed_dim=40, hidden_dim=512, **kwargs)


def get_my_vae(name: str, **kwargs) -> VAE:
    if name == '16k':
        return VAE_16k(**kwargs)
    if name == '44k':
        return VAE_44k(**kwargs)
    raise ValueError(f'Unknown model: {name}')
